---
# This is data for infra-role-dist-validators.
# To search for a validator ID see: ansible/files/layouts/nimbus.holesky.tsv
nodes_layout:
  'geth-01.ih-eu-mda1.nimbus.holesky': # 0 each
    - { branch: 'stable',                              el: 'geth',      vc: true  }
    - { branch: 'testing',                             el: 'geth',      vc: false }
    - { branch: 'unstable',                            el: 'geth',      vc: false, public_api: true }
    - { branch: 'libp2p',                              el: 'geth',      vc: false }

  'geth-02.ih-eu-mda1.nimbus.holesky': # 1 each
    - { branch: 'stable',   start:     0, end:     1,  el: 'geth',      vc: true  }
    - { branch: 'testing',  start:     1, end:     2,  el: 'geth',      vc: false, public_api: true }
    - { branch: 'unstable', start:     2, end:     3,  el: 'geth',      vc: false, rpc_snooper: true }
    - { branch: 'libp2p',   start:     3, end:     4,  el: 'geth',      vc: false }

  'geth-03.ih-eu-mda1.nimbus.holesky': # 4 each
    - { branch: 'stable',   start:     4, end:     8,  el: 'geth',      vc: true  }
    - { branch: 'testing',  start:     8, end:    12,  el: 'geth',      vc: false }
    - { branch: 'unstable', start:    12, end:    16,  el: 'geth',      vc: false }
    - { branch: 'libp2p',   start:    16, end:    20,  el: 'geth',      vc: false }

  'geth-04.ih-eu-mda1.nimbus.holesky': # 3245 each
    - { branch: 'stable',   start:  20,   end:  3265,  el: 'geth',      vc: true  }
    - { branch: 'testing',  start:  3265, end:  6510,  el: 'geth',      vc: false, rpc_snooper: true }
    - { branch: 'unstable', start:  6510, end:  9755,  el: 'geth',      vc: false }
    - { branch: 'libp2p',   start:  9755, end:  13000, el: 'geth',      vc: false }

  'geth-05.ih-eu-mda1.nimbus.holesky': # 5000 each
    - { branch: 'stable',   start: 13000, end: 18000,  el: 'geth',      vc: true, payload_builder: true }
    - { branch: 'testing',  start: 18000, end: 23000,  el: 'geth',      vc: false }
    - { branch: 'unstable', start: 23000, end: 28000,  el: 'geth',      vc: false }
    - { branch: 'libp2p',   start: 28000, end: 33000,  el: 'geth',      vc: false }

  # Nimbus-eth1 ---------------------------------------------------------------------
  'nec-01.ih-eu-mda1.nimbus.holesky': # 0 each
    - { branch: 'stable',                              el: 'nec', vc: false }
    - { branch: 'testing',                             el: 'nec', vc: false }
    - { branch: 'unstable',                            el: 'nec', vc: true  }
    - { branch: 'libp2p',                              el: 'nec', vc: false }

  'nec-02.ih-eu-mda1.nimbus.holesky': # 1 each
    - { branch: 'stable',   start: 33000, end: 33001,  el: 'nec', vc: false }
    - { branch: 'testing',  start: 33001, end: 33002,  el: 'nec', vc: false }
    - { branch: 'unstable', start: 33002, end: 33003,  el: 'nec', vc: true  }
    - { branch: 'libp2p',   start: 33003, end: 33004,  el: 'nec', vc: false, rpc_snooper: true }

  'nec-03.ih-eu-mda1.nimbus.holesky': # 4 each
    - { branch: 'stable',   start: 33004, end: 33008,  el: 'nec', vc: false }
    - { branch: 'testing',  start: 33008, end: 33012,  el: 'nec', vc: false }
    - { branch: 'unstable', start: 33012, end: 33016,  el: 'nec', vc: true  }
    - { branch: 'libp2p',   start: 33016, end: 33020,  el: 'nec', vc: false }

  'nec-04.ih-eu-mda1.nimbus.holesky': # 3245 each
    - { branch: 'stable',   start: 33020, end: 36265,  el: 'nec', vc: false }
    - { branch: 'testing',  start: 36265, end: 39510,  el: 'nec', vc: false }
    - { branch: 'unstable', start: 39510, end: 42755,  el: 'nec', vc: true  }
    - { branch: 'libp2p',   start: 42755, end: 46000,  el: 'nec', vc: false }

  'nec-05.ih-eu-mda1.nimbus.holesky': # 5000 each
    - { branch: 'stable',   start: 46000, end: 51000,  el: 'nec', vc: false, rpc_snooper: true }
    - { branch: 'testing',  start: 51000, end: 56000,  el: 'nec', vc: false }
    - { branch: 'unstable', start: 56000, end: 61000,  el: 'nec', vc: true  }
    - { branch: 'libp2p',   start: 61000, end: 66000,  el: 'nec', vc: false }

  # Nethermind ---------------------------------------------------------------------
  'neth-01.ih-eu-mda1.nimbus.holesky': # 0 each
    - { branch: 'stable',                              el: 'nethermind', vc: false }
    - { branch: 'testing',                             el: 'nethermind', vc: false }
    - { branch: 'unstable',                            el: 'nethermind', vc: true  }
    - { branch: 'libp2p',                              el: 'nethermind', vc: false }

  'neth-02.ih-eu-mda1.nimbus.holesky': # 1 each
    - { branch: 'stable',   start: 66000, end: 66001,  el: 'nethermind', vc: true,  payload_builder: true }
    - { branch: 'testing',  start: 66001, end: 66002,  el: 'nethermind', vc: false }
    - { branch: 'unstable', start: 66002, end: 66003,  el: 'nethermind', vc: false }
    - { branch: 'libp2p',   start: 66003, end: 66004,  el: 'nethermind', vc: false }

  'neth-03.ih-eu-mda1.nimbus.holesky': # 4 each
    - { branch: 'stable',   start: 66004, end: 66008,  el: 'nethermind', vc: true  }
    - { branch: 'testing',  start: 66008, end: 66012,  el: 'nethermind', vc: false }
    - { branch: 'unstable', start: 66012, end: 66016,  el: 'nethermind', vc: true,  payload_builder: true }
    - { branch: 'libp2p',   start: 66016, end: 66020,  el: 'nethermind', vc: false }

  'neth-04.ih-eu-mda1.nimbus.holesky': # 3245 each
    - { branch: 'stable',   start: 66020, end: 69265,  el: 'nethermind', vc: false }
    - { branch: 'testing',  start: 69265, end: 72510,  el: 'nethermind', vc: false }
    - { branch: 'unstable', start: 72510, end: 75755,  el: 'nethermind', vc: true,  payload_builder: true }
    - { branch: 'libp2p',   start: 75755, end: 79000,  el: 'nethermind', vc: false }

  'neth-05.ih-eu-mda1.nimbus.holesky': # 5000 each
    - { branch: 'stable',   start: 79000, end: 84000,  el: 'nethermind', vc: false, payload_builder: true }
    - { branch: 'testing',  start: 84000, end: 89000,  el: 'nethermind', vc: false }
    - { branch: 'unstable', start: 89000, end: 94000,  el: 'nethermind', vc: true, rpc_snooper: true }
    - { branch: 'libp2p',   start: 94000, end: 99993,  el: 'nethermind', vc: false }

  # MacOS --------------------------------------------------------------------------
  'macm2-01.ih-eu-mda1.nimbus.holesky': # 0 each
    - { branch: 'stable',                                  build_start: '13:00:00' }
    - { branch: 'testing',                                 build_start: '15:00:00' }
    - { branch: 'unstable',                                build_start: '17:00:00' }

  # Windows ------------------------------------------------------------------------
  'windows-01.ih-eu-mda1.nimbus.holesky': # 0 each
    - { branch: 'stable',                                  build_start: '13:00:00' }
    - { branch: 'testing',                                 build_start: '15:00:00' }
    - { branch: 'unstable',                                build_start: '17:00:00' }
    - { branch: 'libp2p',                                  build_start: '19:00:00' }

  # Geth ---------------------------------------------------------------------------
  'holesky-01.ih-eu-mda1.nimbus.geth': [{}, {}, {}, {}] # For Windows nodes. (TODO)
