---
# This is data for infra-role-dist-validators.
# To search for a validator ID see: ansible/files/layouts/nimbus.hoodi.tsv
nodes_layout:
  'geth-01.ih-eu-mda1.nimbus.hoodi': # 0 each
    - { branch: 'stable',                             el: 'geth', vc: true  }
    - { branch: 'testing',                            el: 'geth', vc: false }
    - { branch: 'unstable',                           el: 'geth', vc: false, public_api: true }

  'geth-02.ih-eu-mda1.nimbus.hoodi': # 1 each
    - { branch: 'stable',   start:     0, end:    1,  el: 'geth', vc: true  }
    - { branch: 'testing',  start:     1, end:    2,  el: 'geth', vc: false, public_api: true }
    - { branch: 'unstable', start:     2, end:    3,  el: 'geth', vc: false }

  'geth-03.ih-eu-mda1.nimbus.hoodi': # 4 each
    - { branch: 'stable',   start:     3, end:    7,  el: 'geth', vc: true  }
    - { branch: 'testing',  start:     7, end:   11,  el: 'geth', vc: false, rpc_snooper: true }
    - { branch: 'unstable', start:    11, end:   15,  el: 'geth', vc: false }

  'geth-04.ih-eu-mda1.nimbus.hoodi': # 2000 each
    - { branch: 'stable',    start: 15,   end: 2015,  el: 'geth', vc: false, payload_builder: true }
    - { branch: 'testing',   start: 2015, end: 4015,  el: 'geth', vc: false }
    - { branch: 'unstable',  start: 4015, end: 6015,  el: 'geth', vc: true  }

  'geth-05.ih-eu-mda1.nimbus.hoodi': # 3550 each
    - { branch: 'stable',   start: 6015,  end: 9565,  el: 'geth', vc: true,   payload_builder: true }
    - { branch: 'testing',  start: 9565,  end: 13115, el: 'geth', vc: false }
    - { branch: 'unstable', start: 13115, end: 16665, el: 'geth', vc: false }

  # Nimbus-eth1 ---------------------------------------------------------------------
  'nec-01.ih-eu-mda1.nimbus.hoodi': # 0 each
    - { branch: 'stable',                             el: 'nec', vc: false }
    - { branch: 'testing',                            el: 'nec', vc: false }
    - { branch: 'unstable',                           el: 'nec', vc: true  }

  'nec-02.ih-eu-mda1.nimbus.hoodi': # 1 each
    - { branch: 'stable',   start: 16665, end: 16666, el: 'nec', vc: false }
    - { branch: 'testing',  start: 16666, end: 16667, el: 'nec', vc: false }
    - { branch: 'unstable', start: 16667, end: 16668, el: 'nec', vc: true  }

  'nec-03.ih-eu-mda1.nimbus.hoodi': # 4 each
    - { branch: 'stable',   start: 16668, end: 16672, el: 'nec', vc: false }
    - { branch: 'testing',  start: 16672, end: 16676, el: 'nec', vc: false }
    - { branch: 'unstable', start: 16676, end: 16680, el: 'nec', vc: true  }

  'nec-04.ih-eu-mda1.nimbus.hoodi': # 2000 each
    - { branch: 'stable',   start: 16680, end: 18680, el: 'nec', vc: false }
    - { branch: 'testing',  start: 18680, end: 20680, el: 'nec', vc: false, payload_builder: true }
    - { branch: 'unstable', start: 20680, end: 22680, el: 'nec', vc: true  }

  'nec-05.ih-eu-mda1.nimbus.hoodi': # 3550 each
    - { branch: 'stable',   start: 22680, end: 26230, el: 'nec', vc: false }
    - { branch: 'testing',  start: 26230, end: 29780, el: 'nec', vc: false }
    - { branch: 'unstable', start: 29780, end: 33330, el: 'nec', vc: true,  rpc_snooper: true }

  # Nethermind ---------------------------------------------------------------------
  'neth-01.ih-eu-mda1.nimbus.hoodi': # 0 each
    - { branch: 'stable',                             el: 'nethermind', vc: false }
    - { branch: 'testing',                            el: 'nethermind', vc: false }
    - { branch: 'unstable',                           el: 'nethermind', vc: true  }

  'neth-02.ih-eu-mda1.nimbus.hoodi': # 1 each
    - { branch: 'stable',   start: 33330, end: 33331, el: 'nethermind', vc: true,  payload_builder: true }
    - { branch: 'testing',  start: 33331, end: 33332, el: 'nethermind', vc: false }
    - { branch: 'unstable', start: 33332, end: 33333, el: 'nethermind', vc: false }

  'neth-03.ih-eu-mda1.nimbus.hoodi': # 4 each
    - { branch: 'stable',   start: 33333, end: 33337, el: 'nethermind', vc: true  }
    - { branch: 'testing',  start: 33337, end: 33341, el: 'nethermind', vc: false }
    - { branch: 'unstable', start: 33341, end: 33345, el: 'nethermind', vc: true,  payload_builder: true }

  'neth-04.ih-eu-mda1.nimbus.hoodi': # 2000 each
    - { branch: 'stable',   start: 33345, end: 35345, el: 'nethermind', vc: false }
    - { branch: 'testing',  start: 35345, end: 37345, el: 'nethermind', vc: false }
    - { branch: 'unstable', start: 37345, end: 39345, el: 'nethermind', vc: true,  payload_builder: true }

  'neth-05.ih-eu-mda1.nimbus.hoodi': # 3550 each
    - { branch: 'stable',   start: 39345, end: 42895, el: 'nethermind', vc: false, payload_builder: true }
    - { branch: 'testing',  start: 42895, end: 46445, el: 'nethermind', vc: false, rpc_snooper: true }
    - { branch: 'unstable', start: 46445, end: 50000, el: 'nethermind', vc: true  }

  # LibP2P Autobump ----------------------------------------------------------------
  'libp2p-01.ih-eu-mda1.nimbus.hoodi': # 0 each
    - { branch: 'libp2p',   index: '01',              el: 'geth',       vc: false, rpc_snooper: true }
    - { branch: 'libp2p',   index: '02',                                vc: false                    }
    - { branch: 'syncv3',   index: '01',              el: 'nethermind', vc: false, resync: true      }
    - { branch: 'syncv3',   index: '02',                                vc: false, resync: true      }

  # MacOS --------------------------------------------------------------------------
  'macm2-01.ih-eu-mda1.nimbus.hoodi':
    - { branch: 'stable',   build_start: '13:00:00' }
    - { branch: 'testing',  build_start: '15:00:00' }
    - { branch: 'unstable', build_start: '17:00:00' }

  # Windows ------------------------------------------------------------------------
  'windows-01.ih-eu-mda1.nimbus.hoodi': # 0 each
    - { branch: 'stable',   build_start: '13:00:00' }
    - { branch: 'testing',  build_start: '15:00:00' }
    - { branch: 'unstable', build_start: '17:00:00' }
