---
# This is data for infra-role-dist-validators.
nodes_layout:
  # AWS --------------------------------------------------------------
  'bootstrap-01.aws-eu-central-1a.nimbus.mainnet':
    - { branch: 'stable', history: 'archive' }

  'bootstrap-02.aws-eu-central-1a.nimbus.mainnet':
    - { branch: 'stable', history: 'archive' }

  # Innova Hosting ---------------------------------------------------
  'nec-01.ih-eu-mda1.nimbus.mainnet':
    - { branch: 'stable',   el: 'nec' }
    - { branch: 'testing'             }
    - { branch: 'unstable', el: 'nec' }
    - { branch: 'libp2p'              }

  'nec-02.ih-eu-mda1.nimbus.mainnet':
    - { branch: 'stable',   el: 'nec' }
    - { branch: 'testing',            }
    - { branch: 'unstable', el: 'nec' }
    - { branch: 'libp2p'              }

  'nec-03.ih-eu-mda1.nimbus.mainnet':
    - { branch: 'stable',   el: 'nec' }
    - { branch: 'testing'             }
    - { branch: 'unstable', el: 'nec' }
    - { branch: 'libp2p'              }

  'erigon-01.ih-eu-mda1.nimbus.mainnet':
    - { branch: 'stable',   el: 'erigon' }
    - { branch: 'testing'                }
    - { branch: 'unstable', el: 'erigon' }
    - { branch: 'libp2p'                 }

  'erigon-02.ih-eu-mda1.nimbus.mainnet':
    - { branch: 'stable',   el: 'erigon' }
    - { branch: 'testing'                }
    - { branch: 'unstable', el: 'erigon' }
    - { branch: 'libp2p'                 }

  'geth-01.ih-eu-mda1.nimbus.mainnet':
    - { branch: 'stable',   el: 'geth', max_peers: 10000 }
    - { branch: 'testing'                                }
    - { branch: 'unstable', el: 'geth', public_api: true }
    - { branch: 'libp2p'                                 }

  'geth-02.ih-eu-mda1.nimbus.mainnet':
    - { branch: 'stable'                                 }
    - { branch: 'testing',  el: 'geth', public_api: true } # we need one testing node with EL for public_api
    - { branch: 'unstable', el: 'geth'                   }
    - { branch: 'libp2p'                                 }
