---
# This is data for infra-role-dist-validators.
# To search for a validator ID see: ansible/files/layouts/nimbus.prater.tsv
nodes_layout:
  # WARNING: The nodes hosted on AWS are bootstrap nodes and should not be changed.
  'stable-large-01.aws-eu-central-1a.nimbus.prater': # 2000 each
    - { branch: 'stable',   start:     0, end:  2000, history: 'archive' }

  'testing-large-01.aws-eu-central-1a.nimbus.prater': # 2000 each
    - { branch: 'testing',  start:  2000, end:  4000, history: 'archive' }

  'unstable-large-01.aws-eu-central-1a.nimbus.prater': # 2000 each
    - { branch: 'unstable', start:  4000, end:  6000, history: 'archive', payload_builder: true }

  'macm1-01.ih-eu-mda1.nimbus.prater': # 3000 each
    - { branch: 'stable',   start:  6000, end:  9000, build_start: '13:00:00' }
    - { branch: 'testing',  start:  9000, end: 12000, build_start: '15:00:00' }
    - { branch: 'unstable', start: 12000, end: 14000, build_start: '17:00:00' }

  'windows-01.he-eu-hel1.nimbus.prater': # 2000 each
    - { branch: 'stable',   start: 14000, end: 16000, build_start: '13:00:00' }
    - { branch: 'testing',  start: 16000, end: 18000, build_start: '15:00:00' }
    - { branch: 'unstable', start: 18000, end: 20000, build_start: '16:00:00', nim_flags: '-d:json_rpc_websocket_package=websock' }

  'windows-01.ih-eu-mda1.nimbus.prater':
    - { branch: 'stable',                             build_start: '13:00:00' }
    - { branch: 'testing',                            build_start: '15:00:00' }
    - { branch: 'unstable',                           build_start: '16:00:00', nim_flags: '-d:json_rpc_websocket_package=websock' }

  # Innova Hosting
  'linux-01.ih-eu-mda1.nimbus.prater': # 0 each
    - { branch: 'stable',                             build_freq: '*-*-* 13:00:00' }
    - { branch: 'testing',                            build_freq: '*-*-* 15:00:00' }
    - { branch: 'unstable',                           build_freq: '*-*-* 17:00:00', public_api: true }
    - { branch: 'libp2p',                             build_freq: '*-*-* 19:00:00' }

  'linux-02.ih-eu-mda1.nimbus.prater': # 1 each
    - { branch: 'stable',   start: 20000, end: 20001, build_freq: '*-*-* 13:00:00' }
    - { branch: 'testing',  start: 20001, end: 20002, build_freq: '*-*-* 15:00:00', public_api: true }
    - { branch: 'unstable', start: 20002, end: 20003, build_freq: '*-*-* 17:00:00', nethermind: true }
    - { branch: 'libp2p',   start: 20003, end: 20004, build_freq: '*-*-* 19:00:00' }

  'linux-03.ih-eu-mda1.nimbus.prater': # 10 each
    - { branch: 'stable',   start: 20004, end: 20014, build_freq: '*-*-* 11:00:00' }
    - { branch: 'testing',  start: 20024, end: 20034, build_freq: '*-*-* 15:00:00' }
    - { branch: 'unstable', start: 20014, end: 20024, build_freq: '*-*-* 13:00:00', validator_client: true, open_libp2p_ports: false }
    - { branch: 'libp2p',   start: 20034, end: 20044, build_freq: '*-*-* 17:00:00' }

  'linux-04.ih-eu-mda1.nimbus.prater': # 30 each
    - { branch: 'stable',   start: 20044, end: 20074, build_freq: '*-*-* 11:00:00', validator_client: true }
    - { branch: 'testing',  start: 20104, end: 20134, build_freq: '*-*-* 15:00:00' }
    - { branch: 'unstable', start: 20074, end: 20104, build_freq: '*-*-* 13:00:00', nethermind: true, payload_builder: true }
    - { branch: 'libp2p',   start: 20134, end: 20164, build_freq: '*-*-* 17:00:00' }

  'linux-05.ih-eu-mda1.nimbus.prater': # 60 each
    - { branch: 'stable',   start: 20164, end: 20224, build_freq: '*-*-* 11:00:00' }
    - { branch: 'testing',  start: 20284, end: 20344, build_freq: '*-*-* 15:00:00' }
    - { branch: 'unstable', start: 20224, end: 20284, build_freq: '*-*-* 13:00:00', open_libp2p_ports: false, erigon: true }
    - { branch: 'libp2p',   start: 20344, end: 20404, build_freq: '*-*-* 17:00:00' }

  'linux-06.ih-eu-mda1.nimbus.prater':
    - { branch: 'stable',   start: 20404, end: 29617, build_freq: '*-*-* 11:00:00' } # 9213 validators
    - { branch: 'testing',  start: 29617, end: 37617, build_freq: '*-*-* 15:00:00', validator_client: true, payload_builder: true, open_libp2p_ports: false } # 8000 validators
    - { branch: 'unstable', start: 37617, end: 43617, build_freq: '*-*-* 13:00:00', payload_builder: true  } # 6000 validators
    - { branch: 'libp2p',   start: 43617, end: 49617, build_freq: '*-*-* 17:00:00', validator_client: true } # 6000 validators
