---
# This is data for infra-role-dist-validators.
# To search for a validator ID see: ansible/files/layouts/nimbus.sepolia.tsv
nodes_layout:
  'linux-01.ih-eu-mda1.nimbus.sepolia':
    - { branch: 'stable',   start:  0, end:  30, el: 'geth', vc: true,  payload_builder: true }
    - { branch: 'testing',  start: 30, end:  60, el: 'geth', vc: false, payload_builder: true }
    - { branch: 'unstable', start: 60, end: 100, el: 'geth', vc: false, public_api: true      }
