---
beacon_node_payload_builder_enabled: true
beacon_node_payload_builder_url: 'http://localhost:{{ mev_boost_cont_port }}'
validator_client_payload_builder_enabled: true

mev_boost_enabled: true
mev_boost_network: 'holesky'
mev_boost_relays:
  - 'https://0xaa58208899c6105603b74396734a6263cc7d947f444f396a90f7b7d3e65d102aec7e5e5291b27e08d02c50a050825c2f@holesky.titanrelay.xyz'
