---
# Communityu test REST API endpoint.
beacon_node_rest_address: '0.0.0.0'

# WARNING: This will change if number of nodes changes.
redirect_ports:
  # beacon-node-holesky-unstable
  - { src: 80, dst: 9303, comment: 'Test Beacon API (80->9303/tcp)' }
