---
# Communityu test REST API endpoint.
beacon_node_rest_address: '0.0.0.0'

# Extract dynamically port form layout.
test_api_beacon_node_rest_index: |-
  {{ nodes_layout[hostname]
  | ansible.utils.index_of(test='eq', key='public_api', value=True) }}
test_api_beacon_node_rest_port: |-
  {{ beacon_node_rest_port_base + test_api_beacon_node_rest_index|int + 1 }}
test_api_beacon_node_branch: |-
  {{ nodes_layout[hostname][test_api_beacon_node_rest_index|int].branch }}

# WARNING: This will change if number of nodes changes.
redirect_ports:
  - src: 80
    dst: '{{ test_api_beacon_node_rest_port }}'
    comment: 'Test Beacon API ({{ test_api_beacon_node_branch }})'

# Era files hosting
era_files_domain: 'holesky.era.nimbus.team'
era_files_path: '/data/era'

# CloudFlare Origin certificates
origin_certs:
  - domain: 'nimbus.team'
    crt: '{{lookup("bitwarden", "CloudFlare/nimbus.team", file="origin.crt")}}'
    key: '{{lookup("bitwarden", "CloudFlare/nimbus.team", file="origin.key")}}'

nginx_sites:
  era_files:
    - listen 80 default_server
    - listen 443 ssl

    - server_name {{ era_files_domain }}

    - ssl_certificate     /certs/nimbus.team/origin.crt
    - ssl_certificate_key /certs/nimbus.team/origin.key

    - location / {
        root {{ era_files_path }};
        autoindex on;
        autoindex_format html;
      }
