---
# Community test REST API endpoint.
beacon_node_rest_address: '0.0.0.0'

# Extract dynamically port form layout.
test_api_beacon_node_rest_index: |-
  {{ nodes_layout[inventory_hostname]
  | ansible.utils.index_of(test='eq', key='public_api', value=True) }}
test_api_beacon_node_rest_port: |-
  {{ beacon_node_rest_port_base + test_api_beacon_node_rest_index|int + 1 }}
test_api_beacon_node_branch: |-
  {{ nodes_layout[inventory_hostname][test_api_beacon_node_rest_index|int].branch }}

# WARNING: This will change if number of nodes changes.
redirect_ports:
  public-beacon-api:
    src: 80
    dst: '{{ test_api_beacon_node_rest_port }}'
    comment: 'Test Beacon API ({{ test_api_beacon_node_branch }})'

# Era files hosting
era_files_domain: 'hoodi.era.nimbus.team'
era_files_path: '/docker/era'

# CloudFlare Origin certificates
origin_certs:
  - domain: 'nimbus.team'
    crt: '{{lookup("vault", "certs/cloudflare/nimbus.team", field="origin.crt", stage="all", env="all")}}'
    key: '{{lookup("vault", "certs/cloudflare/nimbus.team", field="origin.key", stage="all", env="all")}}'

nginx_sites:
  era_files:
    - listen 443 ssl

    - server_name {{ era_files_domain }}

    - ssl_certificate     /certs/nimbus.team/origin.crt
    - ssl_certificate_key /certs/nimbus.team/origin.key

    - location / {
        root {{ era_files_path }};
        autoindex on;
        autoindex_format html;
      }
