---
open_ports_list:
  exec-node:
    - { port: '30304-30314', comment: '{{ host_el_type }} LibP2P',    protocol: 'tcp'                     }
    - { port: '30304-30314', comment: '{{ host_el_type }} Discovery', protocol: 'udp'                     }
    - { port: '6061-6064',   comment: '{{ host_el_type }} Metrics',   ipset: 'hq.metrics', iifname: 'wg0' }
    - { port: '9401-9404',   comment: '{{ host_el_type }} Exporter',  ipset: 'hq.metrics', iifname: 'wg0' }
    - { port: '8551-8555',   comment: '{{ host_el_type }} RPC',       ipset: '{{ env }}.{{ stage }}', iifname: 'wg0' }
  nimbus-light-client:
    - { port: '9503',        comment: 'Nimbus Light Client LibP2P',    protocol: 'tcp' }
    - { port: '9503',        comment: 'Nimbus Light Client Discovery', protocol: 'udp' }
