---
bootstrap__extra_volume_devices:
  - 'disk/by-id/scsi-0HP_LOGICAL_VOLUME_01000000'
  - 'disk/by-id/scsi-0HP_LOGICAL_VOLUME_03000000'
bootstrap__extra_volume_bind_paths:
  DATA_VOLUME1: ['/data']
  DATA_VOLUME2: ['/docker']

# Eth1 DB files hosting
eth1_db_files_domain: 'eth1-db.nimbus.team'
eth1_db_files_path: '/docker/nimbus-eth1-db'

# Beacon Nodes -----------------------------------------------------------------
beacon_node_service_name: 'beacon-node-{{ beacon_node_network }}-{{ node.branch }}-{{ node.index }}'
beacon_node_repo_branch: '{{ node_name_to_branch_map.get(node.branch, node.branch) }}'
beacon_node_subscribe_all: '{{ node.branch == "libp2p" and node.index == "01" }}'
# Temporary fix for broken BN build
node_name_to_branch_map:
  libp2p: 'nim-libp2p-auto-bump-unstable'

# CloudFlare Origin certificates -----------------------------------------------
origin_certs:
  - domain: 'nimbus.team'
    crt: '{{lookup("bitwarden", "CloudFlare/nimbus.team", file="origin.crt")}}'
    key: '{{lookup("bitwarden", "CloudFlare/nimbus.team", file="origin.key")}}'

nginx_sites:
  eth1_db:
    - listen 443 ssl

    - server_name {{ eth1_db_files_domain }}

    - ssl_certificate     /certs/nimbus.team/origin.crt
    - ssl_certificate_key /certs/nimbus.team/origin.key

    - location / {
        root {{ eth1_db_files_path }};
        autoindex on;
        autoindex_format html;
      }

    - location = /README.md {
        root /data/nimbus-eth1-db;
        default_type text/plain;
        add_header Content-Type text/plain;
     }

# ERA files generation ---------------------------------------------------------
# Override default path since this host doesn't have an 'unstable' node
nimbus_era_files_db_path: '/data/beacon-node-{{ beacon_node_network }}-libp2p-01/data/db'
