---
# Docker image builds
beacon_node_builds_docker_hub_user: '{{lookup("passwordstore", "cloud/DockerHub/user")}}'
beacon_node_builds_docker_hub_token: '{{lookup("passwordstore", "cloud/DockerHub/token")}}'

# The -small suffix is because of native compilation
beacon_node_builds_branches:
  - name: 'stable-metal-01'
    version: 'stable'
    targets: ['nimbus_beacon_node', 'nimbus_signing_process']
    frequency: '*-*-* 12:00:00'
