---
# Go-Ethereum
geth_service_name: 'aztec-geth-sepolia'
geth_service_path: '/docker/{{ geth_service_name }}'
geth_network_name: 'sepolia'
geth_cont_name: '{{ geth_service_name }}-node'
geth_cont_vol: '{{ geth_service_path }}/node'
geth_sync_mode: 'snap'
geth_log_level_name: info
# Geth auth & JWT token
geth_account_pass:      '{{lookup("vault", "geth", field="password", env="nimbus", stage="all")}}'
geth_authrpc_jwtsecret: '{{ beacon_node_exec_layer_jwt_secret }}'
# Genesis
geth_init_enabled: false
# Ports
geth_rpc_enabled: true
geth_port:         30304
geth_metrics_port: 6061
geth_rpc_port:     8546
geth_authrpc_port: 8552
# Exporter
geth_expo_service_name: '{{ geth_service_name }}'
geth_expo_source_cont_name: '{{ geth_cont_name }}'
geth_expo_source_data_path: '{{ geth_cont_vol }}/data'
geth_expo_cont_port: 9401

# Beacon Nodes
beacon_node_service_name: 'aztec-beacon-node-{{ beacon_node_network }}'
beacon_node_network: 'sepolia'
beacon_node_history_retention: 'archive'
# Execution layer Enginer API
beacon_node_exec_layer_urls: ['http://localhost:{{ geth_authrpc_port }}']
beacon_node_exec_layer_jwt_secret: '{{lookup("vault", "engine-api", field="jwt-token", env="nimbus", stage="all")}}'
# Suggests it to the Execution Layer client.
beacon_node_suggested_fee_recipient: '{{lookup("vault", "testnet-wallet", field="address", env="nimbus", stage="all")}}'
# Ports
beacon_node_discovery_port: 9001
beacon_node_listening_port: 9001
beacon_node_metrics_port:   9201
beacon_node_rest_port:      9301

# Aztec Sequencer
aztec_ethereum_hosts: ['http://{{ geth_cont_name }}:{{ geth_rpc_port }}/']
aztec_l1_consensus_host_urls: ['http://{{ ansible_local.wireguard.address }}:{{ beacon_node_rest_port }}/']
aztec_attester_private_key: '{{lookup("vault", "operator", field="key")}}'
aztec_publisher_private_key: '{{ aztec_attester_private_key }}'
aztec_fee_recipient_address: '0x1b2d5831014b0b24a7a6ed1991cb7bb08ec08ad830fb09809623615770c3f28c'
aztec_coinbase_address: '{{lookup("vault", "operator", field="address")}}'
aztec_cont_networks: ['{{ geth_service_name }}_default']

# Open Ports
open_ports_list:
  aztec-geth:
    - { port: '{{ geth_port }}',                  comment: 'Geth LibP2P',           protocol: 'tcp'                     }
    - { port: '{{ geth_port }}',                  comment: 'Geth Discovery',        protocol: 'udp'                     }
    - { port: '{{ geth_metrics_port }}',          comment: 'Geth Metrics',          ipset: 'hq.metrics', iifname: 'wg0' }
    - { port: '{{ geth_expo_cont_port }}',        comment: 'Geth Metrics',          ipset: 'hq.metrics', iifname: 'wg0' }
  aztec-beacon-node:
    - { port: '{{ beacon_node_listening_port }}', comment: 'Beacon Node libp2p',    protocol: 'tcp'                     }
    - { port: '{{ beacon_node_discovery_port }}', comment: 'Beacon Node discovery', protocol: 'udp'                     }
    - { port: '{{ beacon_node_metrics_port }}',   comment: 'Beacon Node Metrics',   ipset: 'hq.metrics', iifname: 'wg0' }
