---
nimbus_fluffy_service_name: 'nimbus-fluffy-{{ nimbus_fluffy_network }}-{{ nimbus_fluffy_repo_branch }}-{{ "%02d"|format(index|int) }}'
nimbus_fluffy_network: 'mainnet'
nimbus_fluffy_repo_branch: 'master'
# General
nimbus_fluffy_log_level: 'INFO'
# Ports
nimbus_fluffy_host_index: '{{ groups["nimbus.fluffy"].index(inventory_hostname) }}'
nimbus_fluffy_listening_addr: '194.33.43.{{ (32 * (nimbus_fluffy_host_index|int + 1)) + index|int }}'
nimbus_fluffy_public_address: '{{ nimbus_fluffy_listening_addr }}'
nimbus_fluffy_listening_port:   9100
nimbus_fluffy_metrics_port: '{{ 9200 + index|int }}'
nimbus_fluffy_rpc_port:     '{{ 9900 + index|int }}'
# One build for all nodes
nimbus_fluffy_repo_path: '/data/nimbus-fluffy/repo'
nimbus_fluffy_build_service_name: 'build-nimbus-fluffy-{{ nimbus_fluffy_network }}-{{ nimbus_fluffy_repo_branch }}'
nimbus_fluffy_build_restart_service: 'nimbus-fluffy-*.service'
nimbus_fluffy_build_script_path: '/data/nimbus-fluffy/build.sh'
# Consul healthchecks
nimbus_fluffy_consul_check_interval: '60s'
nimbus_fluffy_consul_check_timeout: '10s'
nimbus_fluffy_consul_success_before_passing: 30
nimbus_fluffy_consul_failures_before_warning: 1440
nimbus_fluffy_consul_failures_before_critical: 2880

# Open Ports
open_ports_default_comment: 'SMART Metrics'
open_ports_default_chain: 'VPN'
open_ports_list:
  - { port: '{{ smart_metrics_listen_port }}', ipset: 'metrics.hq' }
