---
swap_file_size_mb: 8192

nimbus_portal_client_service_name: 'nimbus-portal-client-{{ nimbus_portal_client_network }}-{{ nimbus_portal_client_repo_branch }}-{{ "%02d"|format(index|int) }}'
nimbus_portal_client_network: 'mainnet'
nimbus_portal_client_repo_branch: 'master'
# General
nimbus_portal_client_log_level: 'INFO'
nimbus_portal_client_web3_url: 'http://127.0.0.1:{{ nimbus_eth1_http_port }}'
nimbus_portal_client_storage_capacity: '25000'
# Ports
nimbus_portal_client_public_address: '{{ nimbus_portal_client_listening_addr }}'
nimbus_portal_client_listening_port:   9100
nimbus_portal_client_metrics_port: '{{ 9200 + index|int }}'
nimbus_portal_client_rpc_base_port: 9900
nimbus_portal_client_rpc_port: '{{ nimbus_portal_client_rpc_base_port + index|int }}'
# One build for all nodes
nimbus_portal_client_repo_path: '/data/nimbus-portal-client/repo'
nimbus_portal_client_build_service_name: 'build-nimbus-portal-client-{{ nimbus_portal_client_network }}-{{ nimbus_portal_client_repo_branch }}'
nimbus_portal_client_build_restart_service: 'nimbus-portal-client-*.service'
nimbus_portal_client_build_script_path: '/data/nimbus-portal-client/build.sh'
# Consul healthchecks
nimbus_portal_client_consul_check_interval: '60s'
nimbus_portal_client_consul_check_timeout: '10s'
nimbus_portal_client_consul_success_before_passing: 30
nimbus_portal_client_consul_failures_before_warning: 1440
nimbus_portal_client_consul_failures_before_critical: 2880
# Portal Bridge
portal_bridge_portal_client_rpc_port: 19900
portal_bridge_portal_client_listening_port: 19100
portal_bridge_portal_client_metrics_port: 19200
portal_bridge_service_name: 'nimbus-portal-bridge-history'
portal_bridge_command: 'history'
portal_bridge_latest: false
portal_bridge_backfill_mode: 'sync'
portal_bridge_era1_dir: '/era'
portal_bridge_web3_url: 'http://geth-01.ih-eu-mda1.nimbus.mainnet.wg:8545'
portal_bridge_portal_rpc_url: 'http://127.0.0.1:{{ portal_bridge_portal_client_rpc_port }}'

# Nimbus Beacon Node
beacon_node_network: 'mainnet'
beacon_node_repo_branch: 'stable'
beacon_node_service_name: 'beacon-node-{{ beacon_node_network }}-{{ beacon_node_repo_branch }}'
beacon_node_service_path: '/data/{{ beacon_node_service_name }}'

# We don't want alerts outside of working hours
beacon_node_update_frequency: 'Mon..Fri *-*-* 12:00:00 UTC'

# Checkpoint Sync
beacon_node_resync_enabled: true
beacon_node_resync_timer_enabled: false
beacon_node_resync_timer_trusted_api_url: 'http://testing.mainnet.beacon-api.nimbus.team'

# Ports
beacon_node_metrics_port: 9200
beacon_node_rest_port: 5052
beacon_node_rest_address: '0.0.0.0'
beacon_node_discovery_port: 9000
beacon_node_listening_port: 9000
# WebSocket or HTTP URLs for execution layet Engine API
beacon_node_exec_layer_jwt_secret: '{{ nimbus_eth1_jwt_secret }}'
beacon_node_exec_layer_urls: ['http://localhost:{{ nimbus_eth1_engine_http_port }}']

# Nimbus ETH1 ------------------------------------------------------------------

nimbus_eth1_service_name: 'nimbus-eth1-{{ nimbus_eth1_network }}-{{ nimbus_eth1_repo_branch }}'
nimbus_eth1_repo_branch: 'master'
nimbus_eth1_network: 'mainnet'
nimbus_eth1_max_peers: 160
nimbus_eth1_log_level: 'DEBUG'
nimbus_eth1_service_path: '/data/{{ nimbus_eth1_service_name }}'
nimbus_eth1_engine_http_enabled: true
nimbus_eth1_engine_ws_enabled: true
nimbus_eth1_rpc_api: ['eth', 'debug']
nimbus_eth1_portal_enabled: true
# Connect to first portal client for history queries
nimbus_eth1_portal_rpc_url: 'http://127.0.0.1:{{ nimbus_portal_client_rpc_base_port + 1 }}'

# Ports
nimbus_eth1_listening_port:   30303
nimbus_eth1_discovery_port:   30303
nimbus_eth1_http_port:        8545
nimbus_eth1_metrics_port:     9093
nimbus_eth1_engine_http_port: 8550
nimbus_eth1_metrics_address: '0.0.0.0'
# API secert
nimbus_eth1_jwt_secret: '{{lookup("vault", "engine-api", field="jwt-token", stage="all")}}'

# Migrated to NFTables from IPTables.
# https://github.com/status-im/infra-misc/issues/301
bootstrap__firewall_nftables: true

# Open Ports -------------------------------------------------------------------
open_ports_list:
  nimbus-portal-client:
    - { comment: 'Nimbus Portal Client',         port: '{{ nimbus_portal_client_listening_port }}',                                                        protocol: 'udp' }
    - { comment: 'Nimbus Portal Client Metrics', port: '9201-92{{ nimbus_portal_client_host_number_of_public_ips }}', ipset: 'hq.metrics', iifname: 'wg0', protocol: 'tcp' }
  beacon-node:
    - { comment: 'Beacon Node Metrics',   port: '{{ beacon_node_metrics_port }}',   ipset: 'hq.metrics',            iifname: 'wg0' }
    - { comment: 'Beacon Node REST API',  port: '{{ beacon_node_rest_port }}',      ipset: '{{ env }}.{{ stage }}', iifname: 'wg0' }
    - { comment: 'Beacon Node libp2p',    port: '{{ beacon_node_listening_port }}', protocol: 'tcp'                                }
    - { comment: 'Beacon Node discovery', port: '{{ beacon_node_discovery_port }}', protocol: 'udp'                                }
  exec-node:
    - { comment: 'Nimbus-Eth1 LibP2P',    port: '{{ nimbus_eth1_listening_port }}',   protocol: 'tcp'                                }
    - { comment: 'Nimbus-Eth1 Discovery', port: '{{ nimbus_eth1_discovery_port }}',   protocol: 'udp'                                }
    - { comment: 'Nimbus-Eth1 Metrics',   port: '{{ nimbus_eth1_metrics_port }}',     ipset: 'hq.metrics',            iifname: 'wg0' }
    - { comment: 'Nimbus-Eth1 RPC',       port: '{{ nimbus_eth1_http_port }}',        ipset: '{{ env }}.{{ stage }}', iifname: 'wg0' }
    - { comment: 'Nimbus-Eth1 Auth RPC',  port: '{{ nimbus_eth1_engine_http_port }}', ipset: '{{ env }}.{{ stage }}', iifname: 'wg0' }
