---
beacon_node_network: 'prater'
# TODO This is to avoid too long service names.
beacon_node_repo_branch: >-
  {{ node.branch_override is defined | ternary(
       node.branch_override,
       ((node.branch == "libp2p") | ternary("nim-libp2p-auto-bump-unstable", node.branch))
     ) }}
beacon_node_nim_commit: '{{ node.get("nim_commit", "") }}'
# TODO Drop this once all nodes have an number.
service_number: '{{ node.get("num", False) | ternary(("-%02d"|format(node.get("num", 0))), "") }}'
beacon_node_service_name: 'beacon-node-{{ beacon_node_network }}-{{ node.branch }}'
# Ports
beacon_node_discovery_port: '{{ 9000 + port_offset }}'
beacon_node_listening_port: '{{ 9000 + port_offset }}'
beacon_node_metrics_port:   '{{ 9200 + port_offset }}'
beacon_node_rest_port:      '{{ 9300 + port_offset }}'
# Firewall
beacon_node_firewall_libp2p_open: '{{ node.get("open_libp2p_ports", true) }}'
# Tuning
beacon_node_max_peers: 300
beacon_node_threads: >-
  {{ node.num_threads is defined | ternary(
       node.num_threads,
       (node.branch == "testing") | ternary(4, 1)
  ) }}
# Monitoring
beacon_node_validator_monitor_auto: true
beacon_node_validator_monitor_totals: >-
  {{ (node.public_api is defined and node.public_api)
  or (node.end is defined and (node.end - node.start) > 64) }}
# Builds
beacon_node_build_frequency: '{{ node.get("build_freq", "daily") }}'
beacon_node_build_start_time: '{{ node.get("build_start", omit) }}'
# Validators from nimbus-private repo
beacon_node_dist_validators_enabled: '{{ node.start is defined and node.end is defined }}'
beacon_node_dist_validators_start: '{{ node.start | mandatory }}'
beacon_node_dist_validators_end: '{{ node.end | mandatory }}'
# Windows service user
beacon_node_service_user_pass: '{{lookup("bitwarden", "nimbus/windows", field="password")}}'
# HTTP RPC support is unstable
beacon_node_web3_urls: '{{ beacon_node_web3_urls_all | reject("match", "^http://") }}'
# Light client data
beacon_node_light_client_data_enabled: '{{ node.branch in ["unstable", "libp2p"] }}'
beacon_node_light_client_data_serve: true
beacon_node_light_client_data_import: 'only-new'

# Split by hostname for more central location
nodes_layout:
  # WARNING: The nodes hosted on AWS are bootstrap nodes and should not be changed.
  'stable-large-01.aws-eu-central-1a.nimbus.prater': # 2000 each
    - { branch: 'stable',   start:     0, end:  2000 }

  'testing-large-01.aws-eu-central-1a.nimbus.prater': # 2000 each
    - { branch: 'testing',  start:  2000, end:  4000 }

  'unstable-large-01.aws-eu-central-1a.nimbus.prater': # 2000 each
    - { branch: 'unstable', start:  4000, end:  6000 }

  'macos-01.ms-eu-dublin.nimbus.prater': # 2000 each
    - { branch: 'stable',   start:  6000, end:  8000, build_start: '13:00:00' }
    - { branch: 'testing',  start:  8000, end: 10000, build_start: '15:00:00' }
    - { branch: 'unstable', start: 10000, end: 12000, build_start: '16:00:00' }

  'windows-01.he-eu-hel1.nimbus.prater': # 2000 each
    - { branch: 'stable',   start: 12000, end: 14000, build_start: '13:00:00' }
    - { branch: 'testing',  start: 14000, end: 16000, build_start: '15:00:00' }
    - { branch: 'unstable', start: 16000, end: 18000, build_start: '16:00:00' }

  'metal-01.he-eu-hel1.nimbus.prater': # 0 each
    - { branch: 'stable',                             build_freq: '*-*-* 13:00:00' }
    - { branch: 'testing',                            build_freq: '*-*-* 15:00:00' }
    - { branch: 'unstable',                           build_freq: '*-*-* 17:00:00', public_api: true }
    - { branch: 'libp2p',                             build_freq: '*-*-* 19:00:00' }

  'metal-02.he-eu-hel1.nimbus.prater': # 1 each
    - { branch: 'stable',   start: 18000, end: 18001, build_freq: '*-*-* 13:00:00' }
    - { branch: 'testing',  start: 18001, end: 18002, build_freq: '*-*-* 15:00:00', public_api: true }
    - { branch: 'unstable', start: 18002, end: 18003, build_freq: '*-*-* 17:00:00' }
    - { branch: 'libp2p',   start: 18003, end: 18004, build_freq: '*-*-* 19:00:00' }

  'metal-03.he-eu-hel1.nimbus.prater': # 10 each
    - { branch: 'stable',   start: 18004, end: 18014, build_freq: '*-*-* 11:00:00' }
    - { branch: 'testing',  start: 18014, end: 18024, build_freq: '*-*-* 15:00:00' }
    - { branch: 'unstable', start: 18024, end: 18034, build_freq: '*-*-* 13:00:00', open_libp2p_ports: false }
    - { branch: 'libp2p',   start: 18034, end: 18044, build_freq: '*-*-* 17:00:00' }

  'metal-04.he-eu-hel1.nimbus.prater': # 30 each
    - { branch: 'stable',   start: 18044, end: 18074, build_freq: '*-*-* 11:00:00' }
    - { branch: 'testing',  start: 18104, end: 18134, build_freq: '*-*-* 15:00:00' }
    - { branch: 'unstable', start: 18074, end: 18104, build_freq: '*-*-* 13:00:00' }
    - { branch: 'libp2p',   start: 18134, end: 18164, build_freq: '*-*-* 17:00:00' }

  'metal-05.he-eu-hel1.nimbus.prater': # 60 each
    - { branch: 'stable',   start: 18164, end: 18224, build_freq: '*-*-* 11:00:00' }
    - { branch: 'testing',  start: 18284, end: 18344, build_freq: '*-*-* 15:00:00', num_threads: 0, branch_override: 'nim-1.6', nim_commit: 'version-1-6' }
    - { branch: 'unstable', start: 18224, end: 18284, build_freq: '*-*-* 13:00:00', open_libp2p_ports: false }
    - { branch: 'libp2p',   start: 18344, end: 18404, build_freq: '*-*-* 17:00:00' }

  'metal-06.he-eu-hel1.nimbus.prater':
    - { branch: 'stable',   start: 18404, end: 28404, build_freq: '*-*-* 11:00:00' } # 10000 validators
    - { branch: 'testing',  start: 28404, end: 36404, build_freq: '*-*-* 15:00:00', open_libp2p_ports: false, branch_override: 'nim-1.6', nim_commit: 'version-1-6' } # 8000 validators
    - { branch: 'unstable', start: 36404, end: 42404, build_freq: '*-*-* 13:00:00' } # 6000 validators
    - { branch: 'libp2p',   start: 42404, end: 47121, build_freq: '*-*-* 17:00:00' } # 4717 validators
