---
beacon_node_network: 'pyrmont'
beacon_node_cont_tag: 'unstable-{{ (hostname is search("large")) | ternary("large", "small") }}'
dist_validators_layout:
  "unstable-large-01.aws-eu-central-1a.nimbus.pyrmont":  { start: 10750, end: 14750 } # 4000
  "unstable-large-02.aws-eu-central-1a.nimbus.pyrmont":  { start: 14750, end: 16750 } # 2000
  "unstable-small-01.aws-eu-central-1a.nimbus.pyrmont":  { start: 16750, end: 18250 } # 1500
  "unstable-small-02.aws-eu-central-1a.nimbus.pyrmont":  { start: 18250, end: 18850 } # 600
  "unstable-small-03.aws-eu-central-1a.nimbus.pyrmont":  { start: 18850, end: 18999 } # 149
  "unstable-small-04.aws-eu-central-1a.nimbus.pyrmont":  { start: 18999, end: 19000 } # single validator

