---
# Nimbus Eth1 node
nimbus_eth1_repo_branch: 'master'
nimbus_eth1_network: 'mainnet'
nimbus_eth1_max_peers: 160
nimbus_eth1_log_level: 'DEBUG'
# Ports
## EL
nimbus_eth1_listening_port:  30303
nimbus_eth1_discovery_port:  30303
nimbus_eth1_metrics_port:    9093
nimbus_eth1_metrics_address: '0.0.0.0'
## BN
beacon_node_rest_port_base:  9300
beacon_node_rest_port:       '{{ beacon_node_rest_port_base + 1 }}'
beacon_node_discovery_port:  '9001'
beacon_node_listening_port:  '9002'
beacon_node_metrics_port:    '9201'
beacon_node_rest_address:    '0.0.0.0'
beacon_node_max_peers:       '320'

# Beacon Node for bench hosts
beacon_node_repo_branch:     'stable'
beacon_node_network:         'mainnet'
beacon_node_log_level:       'DEBUG'
beacon_node_exec_layer_urls:
  - 'wss://localhost:{{ nimbus_eth1_http_port }}'
  - 'http://localhost:{{ nimbus_eth1_http_port }}'

# Migrated to NFTables from IPTables.
# https://github.com/status-im/infra-misc/issues/301
bootstrap__firewall_nftables: true

# Open Ports -------------------------------------------------------------------
open_ports_list:
  el-node:
    - { port: '{{ nimbus_eth1_listening_port }}', comment: 'Nimbus node listening port', protocol: 'tcp' }
    - { port: '{{ nimbus_eth1_discovery_port }}', comment: 'Nimbus node discovery port', protocol: 'udp' }
    - { port: '{{ nimbus_eth1_metrics_port }}',   comment: 'Nimbus node metrics port', ipset: 'hq.metrics', iifname: 'wg0' }
  beacon-node:
    - { port: '9001-9004', comment: 'Beacon Node libp2p',    protocol: 'tcp' }
    - { port: '9001-9004', comment: 'Beacon Node discovery', protocol: 'udp' }
    - { port: '9201-9204', comment: 'Beacon Node Metrics',   ipset: 'hq.metrics',                iifname: 'wg0' }
    - { port: '9301-9304', comment: 'Beacon Node REST API',  ipset: '{{ env }}.{{ stage }}',     iifname: 'wg0' }
