---
nimbus_fluffy_service_name: 'nimbus-fluffy-{{ nimbus_fluffy_network }}-{{ nimbus_fluffy_repo_branch }}-{{ "%02d"|format(index|int) }}'
nimbus_fluffy_network: 'mainnet'
nimbus_fluffy_repo_branch: 'master'
# General
nimbus_fluffy_log_level: 'INFO'
# Ports
nimbus_fluffy_listening_port: '{{ 9100 + index|int }}'
nimbus_fluffy_metrics_port: '{{ 9200 + index|int }}'
nimbus_fluffy_rpc_port: '{{ 9900 + index|int }}'
# One build for all nodes
nimbus_fluffy_repo_path: '/data/nimbus-fluffy/repo'
nimbus_fluffy_build_service_name: 'build-nimbus-fluffy-{{ nimbus_fluffy_network }}-{{ nimbus_fluffy_repo_branch }}'
nimbus_fluffy_build_restart_service: 'nimbus-fluffy-*.service'
nimbus_fluffy_build_script_path: '/data/nimbus-fluffy/build.sh'
# Bootstrapping nodes
nimbus_fluffy_bootstrap_nodes:
  - 'enr:-IS4QGeTMHteRmm-MSYniUd48OZ1M7RMUsIjnSP_TRbo-goQZAdYuqY2PyNJfDJQBz33kv16k7WB3bZnBK-O1DagvJIBgmlkgnY0gmlwhEFsKgOJc2VjcDI1NmsxoQIQXNgOCBNyoXz_7XP4Vm7pIB1Lp35d67BbC4iSlrrcJoN1ZHCCI40' # nimbus-fluffy-mainnet-master-01@metal-01.he-eu-hel1.nimbus.fluffy
  - 'enr:-IS4QOA4voX3J7-R_x8pjlaxBTpT1S_CL7ZaNjetjZ-0nnr2VaP0wEZsT2KvjA5UWc8vi9I0XvNSd1bjU0GXUjlt7J0BgmlkgnY0gmlwhEFsKgOJc2VjcDI1NmsxoQI7aL5dFuHhwbxWD-C1yWH7UPlae5wuV_3WbPylCBwPboN1ZHCCI44' # nimbus-fluffy-mainnet-master-02@metal-01.he-eu-hel1.nimbus.fluffy
  - 'enr:-IS4QFzPZ7Cc7BGYSQBlWdkPyep8XASIVlviHbi-ZzcCdvkcE382unsRq8Tb_dYQFNZFWLqhJsJljdgJ7WtWP830Gq0BgmlkgnY0gmlwhEFsKq6Jc2VjcDI1NmsxoQPjz2Y1Hsa0edvzvn6-OADS3re-FOkSiJSmBB7DVrsAXIN1ZHCCI40' # nimbus-fluffy-mainnet-master-01@metal-02.he-eu-hel1.nimbus.fluffy
  - 'enr:-IS4QHA1PJCdmESyKkQsBmMUhSkRDgwKjwTtPZYMcbMiqCb8I1Xt-Xyh9Nj0yWeIN4S3sOpP9nxI6qCCR1Nf4LjY0IABgmlkgnY0gmlwhEFsKq6Jc2VjcDI1NmsxoQLMWRNAgXVdGc0Ij9RZCPsIyrrL67eYfE9PPwqwRvmZooN1ZHCCI44' # nimbus-fluffy-mainnet-master-02@metal-02.he-eu-hel1.nimbus.fluffy
# Consul healthchecks
nimbus_fluffy_consul_check_interval: '60s'
nimbus_fluffy_consul_check_timeout: '5s'
nimbus_fluffy_consul_success_before_passing: 5
nimbus_fluffy_consul_failures_before_warning: 720 # 12h
nimbus_fluffy_consul_failures_before_critical: 1440 # 24h

# Open Ports
open_ports_default_comment: 'SMART Metrics'
open_ports_default_chain: 'VPN'
open_ports_list:
  - { port: '{{ smart_metrics_listen_port }}', ipset: 'metrics.hq' }
