---
# Syncing can use a lot of mamory
swap_file_size_mb: 4096

# Geth node
geth_service_name: 'geth-{{ geth_network_name }}-{{ "%02d"|format(idx|int+1) }}'
geth_service_path: '/docker/{{ geth_service_name }}'
geth_cont_name: '{{ geth_service_name }}-node'
geth_cont_vol: '{{ geth_service_path }}/node'
geth_network_name: 'holesky'
geth_sync_mode: 'full'
geth_log_level_name: info
geth_consul_rpc_advertised_address: '{{ inventory_hostname }}.wg'
# Geth auth & JWT token
geth_account_pass:      '{{lookup("vault", "geth",       field="password",  stage="all")}}'
geth_authrpc_jwtsecret: '{{lookup("vault", "engine-api", field="jwt-token", stage="all")}}'
# Memory settings
geth_cont_mem_ratio: 0.8
geth_cache_size: '{{ (ansible_memtotal_mb * 0.25|float) | int }}'
# Ports
geth_port:           '{{ 30303 + (idx|int) + 1 }}'
geth_rpc_port:       '{{ 8545  + (idx|int) + 1 }}'
geth_metrics_port:   '{{ 6060  + (idx|int) + 1 }}'
geth_websocket_port: '{{ 9546  + (idx|int) + 1 }}'
geth_authrpc_port:   '{{ 8551  + (idx|int) + 1 }}'
geth_authrpc_addr:   '0.0.0.0'

# Geth metrics
geth_expo_service_name: '{{ geth_service_name }}'
geth_expo_source_cont_name: '{{ geth_cont_name }}'
geth_expo_source_data_path: '{{ geth_cont_vol }}/data'
geth_expo_cont_port: '{{ 9400 + (idx|int) + 1 }}'

# Migrated to NFTables from IPTables.
# https://github.com/status-im/infra-misc/issues/301
bootstrap__firewall_nftables: true

# Open Ports
open_ports_list:
  geth-node:
    - { port: '6061-6064', comment: 'Geth Metrics',  ipset: 'hq.metrics',     iifname: 'wg0' }
    - { port: '9401-9404', comment: 'Geth Exporter', ipset: 'hq.metrics',     iifname: 'wg0' }
    - { port: '8552-8555', comment: 'Geth',          ipset: 'nimbus.holesky', iifname: 'wg0' }
  smart-metrics:
    - { port: '{{ smart_metrics_listen_port }}', comment: 'SMART Metrics', ipset: 'hq.metrics', iifname: 'wg0' }
