---
# Go-Ethereum
geth_service_name: 'geth-sepolia-{{ "%02d"|format(idx|int+1) }}'
geth_network_name: 'sepolia'
geth_network_id: 11155111
geth_sync_mode: 'snap'
geth_log_level_name: info
# Container
geth_cont_tag: 'v1.10.18'
# Geth auth
geth_account_pass: '{{lookup("bitwarden", "nimbus/geth", field="password")}}'
# Memory settings
geth_cont_mem_ratio: 0.3
# Genesis
geth_init_enabled: false
# Bootstrap
geth_bootnodes:
  - 'enode://9246d00bc8fd1742e5ad2428b80fc4dc45d786283e05ef6edbd9002cbc335d40998444732fbe921cb88e1d2c73d1b1de53bae6a2237996e9bfe14f871baf7066@18.168.182.86:30303'
  - 'enode://ec66ddcf1a974950bd4c782789a7e04f8aa7110a72569b6e65fcd51e937e74eed303b1ea734e4d19cfaec9fbff9b6ee65bf31dcb50ba79acce9dd63a6aca61c7@52.14.151.177:30303'
# Ports
geth_port: '{{ 30303 + idx|int + 11 }}'
geth_metrics_port: '{{ 6060 + idx|int + 11 }}'
geth_rpc_enabled: true
geth_rpc_addr: '0.0.0.0'
geth_rpc_port: '{{ 8545 + idx|int + 11 }}'
geth_websocket_enabled: true
geth_websocket_addr: '0.0.0.0'
geth_websocket_port: '{{ 9546 + idx|int + 11 }}'

nodes_layout:
  'metal-01.he-eu-hel1.nimbus.kiln':
    - { }
    - { }
    - { }
    - { }
