---
# Syncing can use a lot of mamory
swap_file_size_mb: 4096

# Geth node
geth_service_name: 'nimbus-ropsten'
geth_network_name: 'ropsten'
geth_sync_mode: 'snap'
geth_log_level_name: info
geth_websocket_enabled: true
# Enable engine API
geth_rcp_api: 'eth,net,web3,personal,admin,engine'
geth_websocket_api: 'eth,net,web3,personal,admin,engine'
# Geth auth
geth_account_pass: '{{lookup("bitwarden", "nimbus/geth", field="password")}}'
# Allow connections from our VPN
geth_websocket_origins: '*'
# Memory settings
geth_cont_mem_ratio: 0.8
geth_cache_size: '{{ (ansible_memtotal_mb * 0.25|float) | int }}'

# Geth metrics
geth_expo_service_name: '{{ geth_service_name }}'
geth_expo_source_cont_name: '{{ geth_cont_name }}'
geth_expo_source_data_path: '{{ geth_cont_vol }}/data'

# Ports
geth_port: 30303
geth_rpc_addr: '0.0.0.0'
geth_rpc_port: 8545
geth_websocket_addr: '0.0.0.0'
geth_websocket_port: 8546
geth_expo_cont_port: 9200

# Open Ports
open_ports_default_comment: 'Geth API'
open_ports_default_chain: 'VPN'
open_ports_list:
  - { port: '{{ geth_expo_cont_port }}', ipset: 'metrics.hq', comment: 'Geth Metrics' }
  - { port: '{{ geth_websocket_port }}', ipset: 'nimbus.ropsten' }
