---
# Additional disk drive
bootstrap__extra_volume_device_path: '/dev/nvme2n1'
bootstrap__extra_volume_path: '/docker'
bootstrap__extra_volume_bind_path: ''

# Go-Ethereum
geth_service_name: 'nimbus-ropsten-{{ "%02d"|format(idx|int+1) }}'
geth_service_path: '/docker/{{ geth_service_name }}'
geth_network_name: 'ropsten'
geth_cont_name: '{{ geth_service_name }}-node'
geth_cont_vol: '{{ geth_service_path }}/node'
geth_sync_mode: 'snap'
geth_log_level_name: info
# Enable engine API¬
geth_rcp_api: 'eth,net,web3,personal,admin,engine'
# Geth auth
geth_account_pass: '{{lookup("bitwarden", "nimbus/geth", field="password")}}'
geth_authrpc_jwtsecret: '{{lookup("bitwarden", "nimbus/jwt-token")}}'
# Memory settings¬
geth_cont_mem_ratio: 0.15
geth_cache_size: '{{ (ansible_memtotal_mb * 0.1|float) | int }}'

# Geth metrics¬
geth_expo_service_name: '{{ geth_service_name }}'
geth_expo_source_cont_name: '{{ geth_cont_name }}'
geth_expo_source_data_path: '{{ geth_cont_vol }}/data'
geth_expo_cont_port: '{{ 9400 + (idx|int) + 1 }}'

# Ports
geth_port: '{{ 30303 + idx|int + 11 }}'
geth_metrics_port: '{{ 6060 + idx|int + 11 }}'
geth_rpc_enabled: true
geth_rpc_addr: '0.0.0.0'
geth_rpc_port: '{{ 8545 + idx|int + 11 }}'
geth_authrpc_port: '{{ 8551 + (idx|int) + 1 }}'
geth_websocket_port: '{{ 9546 + idx|int + 11 }}'

# Beacon Nodes
beacon_node_service_name: 'beacon-node-{{ beacon_node_network }}-{{ beacon_node_repo_branch }}-{{ "%02d"|format(idx|int+1) }}'
beacon_node_network: 'ropsten'
beacon_node_repo_branch: 'stable'
# Builds
beacon_node_build_frequency: 'daily'
# Monitoring
beacon_node_validator_monitor_auto: true
beacon_node_validator_monitor_totals: true
# HTTP RPC support is unstable
beacon_node_web3_urls: ['ws://localhost:{{ geth_authrpc_port }}']
beacon_node_web3_jwt_secret: '{{ geth_authrpc_jwtsecret }}'
# Ports
beacon_node_discovery_port: '{{ 9000 + idx|int + 1 }}'
beacon_node_listening_port: '{{ 9000 + idx|int + 1 }}'
beacon_node_metrics_port:   '{{ 9200 + idx|int + 1 }}'
beacon_node_rest_port:      '{{ 9300 + idx|int + 1 }}'
beacon_node_rest_address:   '0.0.0.0'
beacon_node_rest_max_headers_size: 1024
# Validators Distribution
beacon_node_dist_validators_enabled: '{{ node.start is defined and node.end is defined }}'
beacon_node_dist_validators_start: '{{ node.validator_client | ternary(0, node.start) | mandatory }}'
beacon_node_dist_validators_end:   '{{ node.validator_client | ternary(0, node.end)   | mandatory }}'
# Suggests it to the Execution Layer client and the builder network.
beacon_node_suggested_fee_recipient: '{{lookup("bitwarden", "nimbus/wallet/testnets", field="address")}}'

# Validator Client
validator_client_service_name: 'validator-client-{{ validator_client_network }}-{{ validator_client_build_repo_branch }}-{{ "%02d"|format(idx|int+1) }}'
validator_client_network: '{{ beacon_node_network }}'
validator_client_log_level: 'INFO'
validator_client_beacon_node_url: 'http://127.0.0.1:{{ beacon_node_rest_port }}'
# Builds
validator_client_build_repo_branch: '{{ beacon_node_repo_branch }}'
validator_client_build_frequency: 'daily'
# Ports
validator_client_metrics_port:    '{{ 8108 + idx|int + 1 }}'
validator_client_keymanager_port: '{{ 5052 + idx|int + 1 }}'
# Suggests it to the Execution Layer client and the builder network.
validator_client_suggested_fee_recipient: '{{lookup("bitwarden", "nimbus/wallet/testnets", field="address")}}'
# MEV Payload Builder
validator_client_payload_builder_enabled: '{{ node.get("payload_builder", false) }}'
# Keymanager
validator_client_keymanager_enabled: true
validator_client_keymanager_token: '{{lookup("bitwarden", "nimbus/keymanager", field="token")}}'
# Validators Distribution
validator_client_dist_validators_enabled: '{{ node.start is defined and node.end is defined }}'
validator_client_dist_validators_start: '{{ (not node.validator_client) | ternary(0, node.start) | mandatory }}'
validator_client_dist_validators_end:   '{{ (not node.validator_client) | ternary(0, node.end)   | mandatory }}'

# Open Ports
open_ports_default_chain: 'VPN'
open_ports_list:
  - { port: '9400:9404', ipset: 'metrics.hq', comment: 'Geth Exporter' }

nodes_layout:
  'metal-01.he-eu-hel1.nimbus.ropsten':
    - { start:     0, end:   500, validator_client: true  } # 500
    - { start:   500, end:  1500, validator_client: true  } # 1000
    - { start:  1500, end:  3500, validator_client: false } # 2000
    - { start:  3500, end: 10000, validator_client: false } # 6500
