---
nimbus_fluffy_service_name: 'nimbus-fluffy-{{ nimbus_fluffy_network }}-{{ nimbus_fluffy_repo_branch }}-{{ "%02d"|format(index|int) }}'
nimbus_fluffy_network: 'mainnet'
nimbus_fluffy_repo_branch: 'master'
# General
nimbus_fluffy_log_level: 'INFO'
# Ports
nimbus_fluffy_public_address: '{{ nimbus_fluffy_listening_addr }}'
nimbus_fluffy_listening_port:   9100
nimbus_fluffy_metrics_port: '{{ 9200 + index|int }}'
nimbus_fluffy_rpc_port:     '{{ 9900 + index|int }}'
# One build for all nodes
nimbus_fluffy_repo_path: '/data/nimbus-fluffy/repo'
nimbus_fluffy_build_service_name: 'build-nimbus-fluffy-{{ nimbus_fluffy_network }}-{{ nimbus_fluffy_repo_branch }}'
nimbus_fluffy_build_restart_service: 'nimbus-fluffy-*.service'
nimbus_fluffy_build_script_path: '/data/nimbus-fluffy/build.sh'
# Consul healthchecks
nimbus_fluffy_consul_check_interval: '60s'
nimbus_fluffy_consul_check_timeout: '10s'
nimbus_fluffy_consul_success_before_passing: 30
nimbus_fluffy_consul_failures_before_warning: 1440
nimbus_fluffy_consul_failures_before_critical: 2880
# Portal Bridge
portal_bridge_fluffy_rpc_port: 19900
portal_bridge_fluffy_listening_port: 19100
portal_bridge_fluffy_metrics_port: 19200
portal_bridge_service_name: 'nimbus-portal-bridge-history'
portal_bridge_command: 'history'
portal_bridge_latest: false
portal_bridge_backfill: true
portal_bridge_audit: true
portal_bridge_era1_dir: '/era'
portal_bridge_web3_url: 'http://geth-01.ih-eu-mda1.nimbus.mainnet.wg:8545'
portal_bridge_portal_rpc_url: 'http://127.0.0.1:{{ portal_bridge_fluffy_rpc_port }}'

# Migrated to NFTables from IPTables.
# https://github.com/status-im/infra-misc/issues/301
bootstrap__firewall_nftables: true

# Open Ports -------------------------------------------------------------------
open_ports_list:
  nimbus-fluffy:
    - { comment: 'Nimbus Fluffy',          port: '{{ nimbus_fluffy_listening_port }}',                                      protocol: 'udp' }
    - { comment: 'Nimbus Fluffy Metrics',  port: '9201-92{{ nimbus_fluffy_host_number_of_public_ips }}',                          ipset: 'hq.metrics', iifname: 'wg0', protocol: 'tcp' }
  smart-metrics:
    - { comment: 'SMART Metrics',          port: '{{ smart_metrics_listen_port }}',    ipset: 'hq.metrics', iifname: 'wg0'                  }
