---
nimbus_portal_client_service_name: 'nimbus-portal-client-{{ nimbus_portal_client_network }}-{{ nimbus_portal_client_repo_branch }}-{{ "%02d"|format(index|int) }}'
nimbus_portal_client_network: 'mainnet'
nimbus_portal_client_repo_branch: 'master'
# General
nimbus_portal_client_log_level: 'INFO'
# Ports
nimbus_portal_client_public_address: '{{ nimbus_portal_client_listening_addr }}'
nimbus_portal_client_listening_port:   9100
nimbus_portal_client_metrics_port: '{{ 9200 + index|int }}'
nimbus_portal_client_rpc_port:     '{{ 9900 + index|int }}'
# One build for all nodes
nimbus_portal_client_repo_path: '/data/nimbus-portal-client/repo'
nimbus_portal_client_build_service_name: 'build-nimbus-portal-client-{{ nimbus_portal_client_network }}-{{ nimbus_portal_client_repo_branch }}'
nimbus_portal_client_build_restart_service: 'nimbus-portal-client-*.service'
nimbus_portal_client_build_script_path: '/data/nimbus-portal-client/build.sh'
# Consul healthchecks
nimbus_portal_client_consul_check_interval: '60s'
nimbus_portal_client_consul_check_timeout: '10s'
nimbus_portal_client_consul_success_before_passing: 30
nimbus_portal_client_consul_failures_before_warning: 1440
nimbus_portal_client_consul_failures_before_critical: 2880
# Portal Bridge
portal_bridge_portal_client_rpc_port: 19900
portal_bridge_portal_client_listening_port: 19100
portal_bridge_portal_client_metrics_port: 19200
portal_bridge_service_name: 'nimbus-portal-bridge-history'
portal_bridge_command: 'history'
portal_bridge_latest: false
portal_bridge_backfill: true
portal_bridge_audit: true
portal_bridge_era1_dir: '/era'
portal_bridge_web3_url: 'http://geth-01.ih-eu-mda1.nimbus.mainnet.wg:8545'
portal_bridge_portal_rpc_url: 'http://127.0.0.1:{{ portal_bridge_portal_client_rpc_port }}'

# Migrated to NFTables from IPTables.
# https://github.com/status-im/infra-misc/issues/301
bootstrap__firewall_nftables: true

# Open Ports -------------------------------------------------------------------
open_ports_list:
  nimbus-portal-client:
    - { comment: 'Nimbus Portal Client',          port: '{{ nimbus_portal_client_listening_port }}',                                      protocol: 'udp' }
    - { comment: 'Nimbus Portal Client Metrics',  port: '9201-92{{ nimbus_portal_client_host_number_of_public_ips }}',                          ipset: 'hq.metrics', iifname: 'wg0', protocol: 'tcp' }
