---
# Volumes
bootstrap__extra_volume_bind_paths:
  DATA_VOLUME1: ['/data', '/docker']

# Rocketpool
rocketpool_eth1_network: 'goerli'
# Ports
rocketpool_metrics_port: 9102
rocketpool_eth2_libp2p_port: 59001
rocketpool_eth2_discovery_port: 59001
rocketpool_eth2_metrics_port: 58008
rocketpool_eth2_rest_port: 55052
rocketpool_eth2_rpc_port: 59190
# Eth1 Sync
# TODO query Consul for these
rocketpool_eth1_exec_layer_jwtsecret: '{{ nimbus_eth1_jwt_secret }}'
rocketpool_eth1_exec_layer_authrpc_url: 'http://localhost:{{ nimbus_eth1_http_port }}'
rocketpool_eth1_exec_layer_rpc_url: 'http://localhost:{{ nimbus_eth1_http_port }}'
rocketpool_eth1_exec_layer_ws_url: 'ws://localhost:{{ nimbus_eth1_http_port }}'
rocketpool_eth1_archive_url: 'http://localhost:{{ nimbus_eth1_http_port }}'
# Eth1 Wallet
rocketpool_password: '{{lookup("passwordstore", "services/Rocketpool/test/Eth1/pass")}}'
rocketpool_wallet: '{{lookup("passwordstore", "services/Rocketpool/test/Eth1/wallet")}}'
# Transaction Fees
rocketpool_eth2_fee_recipient: '{{lookup("bitwarden", "nimbus/wallet/testnets", field="address")}}'

# Nimbus Eth1 node
nimbus_eth1_repo_branch: 'master'
nimbus_eth1_network: 'goerli'
nimbus_eth1_max_peers: 160
nimbus_eth1_log_level: 'DEBUG'
# Ports
nimbus_eth1_metrics_port: 9093
nimbus_eth1_metrics_address: '0.0.0.0'
# API secert
nimbus_eth1_jwt_secret: '{{lookup("bitwarden", "nimbus/jwt-token")}}'
