---
- name: Create ERA files directory
  file:
    path: '{{ nimbus_era_files_timer_path }}'
    owner: '{{ nimbus_era_files_timer_user }}'
    group: '{{ nimbus_era_files_timer_group }}'
    state: 'directory'
    mode:  '0755'

- name: Create ERA generating timer
  include_tasks: '{{ ansible_system | lower }}.yml'
