FROM debian:bullseye-slim

ARG COMMIT

RUN apt-get -qq update \
 && apt-get -qq -y install libpcre3-dev 1>/dev/null \
 && apt-get -qq clean \
 && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY repo/build/nimbus_beacon_node_${COMMIT} /usr/local/bin/nimbus_beacon_node
COPY repo/build/nimbus_signing_process_${COMMIT} /usr/local/bin/nimbus_signing_process

STOPSIGNAL SIGINT

ENTRYPOINT ["/usr/local/bin/nimbus_beacon_node"]

CMD ["--help"]
