FROM debian:bullseye-slim

ARG COMMIT

RUN apt-get -qq update \
 && apt-get -qq -y install libpcre3-dev 1>/dev/null \
 && apt-get -qq clean \
 && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

{% for target in item.targets %}
COPY repo/build/{{ target }}_${COMMIT} /usr/local/bin/{{ target }}
{% endfor %}

STOPSIGNAL SIGINT

ENTRYPOINT ["/usr/local/bin/{{ item.targets | first }}"]

CMD ["--help"]
