# This is the network config written by 'subiquity'
network:
  ethernets:
    eno1:
      critical: true
      dhcp-identifier: mac
#      dhcp4: true
      addresses:
        - 185.181.229.82/24
        - 2a0a:d580:801:60::101/64
        - 2a0a:d580:40:60::121/64
      gateway4: 185.181.229.1
      gateway6: 2a0a:d580:40:60::1
      gateway6: 2a0a:d580:801:60::1
      nameservers:
        addresses:
        - 194.33.40.10
        - 8.8.8.8
        search:
        - iphost.md.
  version: 2
