---
# Nimbus-Eth1 ------------------------------------------------------------------
nimbus_eth1_service_name: 'nimbus-eth1-{{ nimbus_eth1_network }}-{{ nimbus_eth1_repo_branch }}-trial'
nimbus_eth1_repo_branch: 'master'
nimbus_eth1_network: 'sepolia'
nimbus_eth1_max_peers: 160
nimbus_eth1_log_level: 'DEBUG'
nimbus_eth1_metrics_address: '0.0.0.0'
# Kinda hacky way to just add this as 5th node.
nimbus_eth1_rpc_enabled: true
nimbus_eth1_rpc_port: '{{ 8545 + idx|int + 22 }}'
nimbus_eth1_ws_enabled: true
nimbus_eth1_ws_port: '{{ 9546 + idx|int + 22 }}'
nimbus_eth1_jwt_secret:  '{{lookup("bitwarden", "nimbus/jwt-token")}}'

# Beacon Nodes -----------------------------------------------------------------
beacon_node_service_name: 'beacon-node-{{ beacon_node_network }}-{{ beacon_node_repo_branch }}-trial-{{ "%02d"|format(idx|int+1) }}'
beacon_node_network: 'sepolia'
beacon_node_repo_branch: 'unstable'
beacon_node_nim_commit: '{{ node.get("nim_commit", "") }}'
beacon_node_build_nim_flags: '-d:noSignalHandler {{ node.get("nim_flags", "") }}'

#Builds
beacon_node_build_frequency: 'daily'
# Monitoring
beacon_node_validator_monitor_auto: true
beacon_node_validator_monitor_totals: true
#Eth1 Sync
beacon_node_web3_urls: ['ws://localhost:{{ nimbus_eth1_ws_port }}']
beacon_node_web3_jwt_secret: '{{ nimbus_eth1_jwt_secret }}'
# Validators from nimbus-private repo¬
beacon_node_dist_validators_enabled: '{{ node.start is defined and node.end is defined }}'
beacon_node_dist_validators_start: '{{ node.start | mandatory }}'
beacon_node_dist_validators_end: '{{ node.end | mandatory }}'
# Ports
beacon_node_discovery_port: '{{ 9000 + idx|int + 22 }}'
beacon_node_listening_port: '{{ 9000 + idx|int + 22 }}'
beacon_node_metrics_port:   '{{ 9200 + idx|int + 22 }}'
beacon_node_rest_port:      '{{ 9300 + idx|int + 22 }}'
beacon_node_rest_address:   '0.0.0.0'

nodes_layout:
  'metal-01.he-eu-hel1.nimbus.kiln':
    - { }
