---
# Go-Ethereum
geth_service_name: 'geth-kiln-{{ "%02d"|format(idx|int+1) }}'
geth_network_name: 'kiln'
geth_sync_mode: 'snap'
geth_log_level_name: info
# Geth auth
geth_account_pass: '{{lookup("bitwarden", "nimbus/geth", field="password")}}'
# Memory settings
geth_cont_mem_ratio: 0.3
# Genesis
geth_init_enabled: true
geth_init_url: 'https://config.kiln.themerge.dev/el/genesis/geth.json'
geth_init_sha256: 'd882fc918533489bc757683e09f9daba4921bdc4cfa80de27f088aa0ccb671ba'
# Enable engine API
geth_rcp_api: 'eth,net,web3,personal,admin,engine'
geth_websocket_api: 'eth,net,web3,personal,admin,engine'
# Ports
geth_port: '{{ 30303 + idx|int + 1 }}'
geth_metrics_port: '{{ 6060 + idx|int + 1 }}'
geth_rpc_enabled: true
geth_rpc_addr: '0.0.0.0'
geth_rpc_port: '{{ 8545 + idx|int + 1 }}'
geth_websocket_enabled: true
geth_websocket_addr: '0.0.0.0'
geth_websocket_port: '{{ 9546 + idx|int + 1 }}'

# Beacon Nodes
beacon_node_service_name: 'beacon-node-{{ beacon_node_network }}-devauth-{{ "%02d"|format(idx|int+1) }}'
beacon_node_network: 'kiln'
beacon_node_repo_branch: 'kiln-dev-auth'
# Builds
beacon_node_build_frequency: 'daily'
# Monitoring
beacon_node_validator_monitor_auto: true
beacon_node_validator_monitor_totals: true
# Eth1 Sync
beacon_node_web3_urls: ['ws://{{ hostname }}.wg:{{ geth_websocket_port }}']
# Validators from nimbus-private repo
beacon_node_dist_validators_enabled: '{{ node.start is defined and node.end is defined }}'
beacon_node_dist_validators_start: '{{ node.start | mandatory }}'
beacon_node_dist_validators_end: '{{ node.end | mandatory }}'
# Ports
beacon_node_discovery_port: '{{ 9000 + idx|int + 1 }}'
beacon_node_listening_port: '{{ 9000 + idx|int + 1 }}'
beacon_node_metrics_port:   '{{ 9200 + idx|int + 1 }}'
beacon_node_rest_port:      '{{ 9300 + idx|int + 1 }}'
beacon_node_rest_address:   '0.0.0.0'

# Make one of the nodes public
redirect_ports:
  # beacon-node-kiln-devauth-01.service
  - { src: 80, dst: 9301, comment: 'Test Beacon API (80->9301/tcp)' }

nodes_layout:
  'metal-01.he-eu-hel1.nimbus.kiln':
    - { start:   0, end: 125 }
    - { start: 125, end: 250 }
    - { start: 250, end: 375 }
    - { start: 375, end: 500 }
