---
- name: 'Redirect {{ rule.value.src }} to {{ rule.value.dst }}'
  copy:
    dest: '/etc/nft.conf.d/services/{{ rule.key }}.nft'
    content: |
      #!/usr/sbin/nft -f
      # Managed with Ansible: redirect-ports
      tcp dport { {{ rule.value.src | mandatory }}, {{ rule.value.dst | mandatory }} } accept comment "{{ rule.value.comment }}"
  with_dict: '{{ redirect_ports | mandatory }}'
  loop_control:
    loop_var: 'rule'
    label: '{{ rule.key }}'
  notify:
    - Reload nftables

- name: 'Redirect {{ rule.value.src }} to {{ rule.value.dst }}'
  copy:
    dest: '/etc/nft.conf.d/prerouting/{{ rule.key }}.nft'
    content: |
      #!/usr/sbin/nft -f
      iifname {{ redirect_interface }} tcp dport {{ rule.value.src | mandatory }} redirect to {{ rule.value.dst | mandatory }} comment "{{ rule.value.comment }}"
  with_dict: '{{ redirect_ports | mandatory }}'
  loop_control:
    loop_var: 'rule'
    label: '{{ rule.key }}'
  notify:
    - Reload nftables
