---
- name: Verify Ansible versions
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./roles.py --check
      changed_when: false

- name: Deploy Aztect Sequencer Node
  become: true
  vars_files: aztect-testnet.yml
  hosts:
    - aztec.sepolia
  pre_tasks:
    - name: Enable Maintenance Mode
      command: 'maintenance Ansible run by {{ lookup("env", "USER") }}'
      tags: always
  post_tasks:
    - name: Disable Maintenance Mode
      command: 'maintenance disable'
      tags: always
  roles:
    - { role: infra-role-open-ports,        tags: open-ports       }
    - { role: infra-role-geth,              tags: geth             }
    - { role: infra-role-geth-exporter,     tags: geth-exporter    }
    - { role: infra-role-beacon-node-linux, tags: beacon-node      }
    - { role: infra-role-aztec,             tags: aztec            }
