---
- name: Verify Ansible versions
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./versioncheck.py
      changed_when: false

- name: Configure ERA files hosting
  become: true
  hosts:
    - linux-03.ih-eu-mda1.nimbus.mainnet
    - linux-01.ih-eu-mda1.nimbus.sepolia
    - geth-01.ih-eu-mda1.nimbus.holesky
  vars:
    open_ports_default_comment: 'Nginx'
    open_ports_default_chain: 'SERVICES'
    open_ports_list: [ { port: 80 }, { port: 443 } ]
  roles:
    - { role: infra-role-open-ports,   tags: open-ports   }
    - { role: infra-role-origin-certs, tags: origin-certs }
    - { role: infra-role-nginx,        tags: nginx        }
