---
- name: Verify Ansible versions
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./versioncheck.py
      changed_when: false

- name: Configure ERA files hosting
  become: true
  hosts:
    - metal-03.he-eu-hel1.nimbus.mainnet
    - linux-01.he-eu-hel1.nimbus.prater
  vars:
    open_ports_default_comment: 'Nginx'
    open_ports_default_chain: 'SERVICES'
    open_ports_list: [ { port: 80 }, { port: 443 } ]
  roles:
    - role: open-ports
      tags: open-ports
    - role: origin-certs
      tags: origin-certs
    - role: nginx
      tags: nginx
