---
- name: Verify Ansible versions
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./roles.py --check
      changed_when: false

- name: Configure ERA & ERA1 files hosting
  become: true
  hosts:
    - erigon-01.ih-eu-mda1.nimbus.mainnet
    - nec-01.ih-eu-mda1.nimbus.mainnet
    - linux-01.ih-eu-mda1.nimbus.sepolia
    - geth-01.ih-eu-mda1.nimbus.holesky
  roles:
    - { role: infra-role-open-ports,   tags: open-ports   }
    - { role: infra-role-origin-certs, tags: origin-certs }
    - { role: infra-role-nginx,        tags: nginx        }
