---
- name: Verify Ansible versions
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./roles.py --check
      changed_when: false

- name: Configure Nimbus Fluffy nodes
  become: true
  hosts:
    - nimbus-fluffy-metal
  roles:
    # Extra 32 or 64 IPv4 addresses for each of the nodes on the host.
    - { role: update-netplan,           tags: update-netplan }
    - { role: infra-role-open-ports,    tags: open-ports     }
  tasks:
    - include_role:
        name: infra-role-nimbus-fluffy
        apply:
          tags: always
      tags: [ nimbus-fluffy ]
      with_sequence: start=1 end={{ nimbus_fluffy_host_number_of_public_ips }}
      loop_control:
        loop_var: index

- name: Configure Nimbus Portal Bridge
  become: true
  vars_files: portal-bridge.yml
  hosts:
    - metal-01.ih-eu-mda1.nimbus.fluffy
  roles:
    - { role: infra-role-open-ports,    tags: open-ports    }
    - { role: infra-role-nimbus-fluffy, tags: nimbus-fluffy }
    - { role: infra-role-portal-bridge, tags: portal-bridge }

- name: Configure Nimbus Fluffy droplet
  become: true
  hosts:
    - nimbus-fluffy-droplet
  roles:
    - { role: infra-role-swap-file,     tags: swap-file      }
    - { role: infra-role-open-ports,    tags: open-ports     }
    - { role: infra-role-nimbus-fluffy, tags: nimbus-fluffy  }
