---
- name: Verify Ansible versions
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./roles.py --check
      changed_when: false

- name: Configure Nimbus Fluffy nodes
  become: true
  hosts:
    - nimbus.fluffy
  roles:
    - { role: infra-role-open-ports,    tags: open-ports    }
    - { role: infra-role-smart-metrics, tags: smart-metrics }
  tasks:
    - include_role: name=infra-role-nimbus-fluffy
      tags: [ beacon-node, infra-role-nimbus-fluffy ]
      with_sequence: start=1 end=32
      loop_control:
        loop_var: index

- name: Configure Nimbus Portal Bridge
  become: true
  hosts:
    - metal-01.ih-eu-mda1.nimbus.fluffy
  roles:
    - { role: infra-role-portal-bridge, tags: portal-bridge }
