---
- name: 'Verify Ansible versions'
  hosts: all
  run_once: true
  connection: local
  tags: always
  gather_facts: false
  tasks:
    - local_action: command ./versioncheck.py
      changed_when: false

- name: Configure geth nodes
  become: true
  hosts:
    - nimbus-geth-goerli
    - nimbus-geth-mainnet
  roles:
    - { role: swap-file,                tags: swap-file }
    - { role: infra-role-geth,          tags: infra-role-geth }
    - { role: infra-role-geth-exporter, tags: infra-role-geth-exporter }
