---
- name: Verify Ansible versions
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./roles.py --check
      changed_when: false

- name: Configure geth nodes
  become: true
  hosts:
    - nimbus-geth-mainnet
  pre_tasks:
    - name: Enable Maintenance Mode
      command: 'maintenance Ansible run by {{ lookup("env", "USER") }}'
      tags: always
  post_tasks:
    - name: Disable Maintenance Mode
      command: 'maintenance disable'
      tags: always
  roles:
    - { role: infra-role-open-ports,    tags: open-ports }
    - { role: infra-role-geth,          tags: geth }
    - { role: infra-role-geth-exporter, tags: geth-exporter }

- name: Deploy Geth nodes for Windows
  become: true
  serial: '{{ serial|default(1) }}'
  vars_files: layout/holesky.yml
  hosts:
    - nimbus-geth-holesky
  pre_tasks:
    - name: Enable Maintenance Mode
      command: 'maintenance Ansible run by {{ lookup("env", "USER") }}'
      tags: always
  post_tasks:
    - name: Disable Maintenance Mode
      command: 'maintenance disable'
      tags: always
  roles:
    - { role: infra-role-open-ports,    tags: open-ports }
  tasks:
    - include_role:
        name: infra-role-geth
        apply:
          tags: always
      tags: [ geth, infra-role-geth ]
      with_items: '{{ nodes_layout[inventory_hostname] }}'
      loop_control:
        loop_var: node
        index_var: idx
    - include_role:
        name: infra-role-geth-exporter
        apply:
          tags: always
      tags: [ geth-exporter, infra-role-geth-exporter ]
      with_items: '{{ nodes_layout[inventory_hostname] }}'
      loop_control:
        loop_var: node
        index_var: idx
