---
- name: Verify Ansible versions
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./roles.py --check
      changed_when: false

- name: Configure geth nodes
  become: true
  hosts:
    - nimbus-geth-mainnet
  roles:
    - { role: infra-role-open-ports,    tags: open-ports }
    - { role: infra-role-smart-metrics, tags: smart-metrics }
    - { role: infra-role-geth,          tags: infra-role-geth }
    - { role: infra-role-geth-exporter, tags: infra-role-geth-exporter }

- name: Deploy Geth nodes for Windows
  become: true
  serial: '{{ serial|default(1) }}'
  vars_files: layout/holesky.yml
  hosts:
    - nimbus-geth-holesky
  roles:
    - { role: infra-role-open-ports,    tags: open-ports }
    - { role: infra-role-smart-metrics, tags: smart-metrics }
  tasks:
    - include_role: name=infra-role-geth
      tags: [ geth, infra-role-geth ]
      with_items: '{{ nodes_layout[inventory_hostname] }}'
      loop_control:
        loop_var: node
        index_var: idx
    - include_role: name=infra-role-geth-exporter
      tags: [ geth-exporter, infra-role-geth-exporter ]
      with_items: '{{ nodes_layout[inventory_hostname] }}'
      loop_control:
        loop_var: node
        index_var: idx
