---
- name: Verify Ansible versions
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./versioncheck.py
      changed_when: false

- name: Deploy Holesky Beacon Nodes
  become: true
  serial: '{{ serial|default(1) }}'
  hosts: nimbus.holesky
  vars_files: layout/holesky.yml
  tasks:
    - include_role: name=infra-role-beacon-node-linux
      with_items: '{{ nodes_layout[hostname] }}'
      loop_control: { loop_var: node, index_var: idx }
