---
- name: Verify Ansible versions
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./versioncheck.py
      changed_when: false

- name: Deploy Holesky Linux Beacon Nodes
  become: true
  serial: '{{ serial|default(1) }}'
  hosts:
    - nimbus-holesky-geth
    - nimbus-holesky-erigon
    - nimbus-holesky-neth
  vars_files: layout/holesky.yml
  roles:
    - role: update-netplan
      tags: update-netplan
      when: ansible_system == 'Linux'
  tasks:
    - include_role: name=infra-role-beacon-node-linux
      with_items: '{{ nodes_layout[hostname] }}'
      loop_control: { loop_var: node, index_var: idx }

- name: Deploy Holesky MacOS Beacon Nodes
  become: true
  hosts:
    - nimbus-holesky-macm2
  vars_files: layout/holesky.yml
  tasks:
    - include_role: name=infra-role-beacon-node-macos
      with_items: '{{ nodes_layout[hostname] }}'
      loop_control: { loop_var: node, index_var: idx }

- name: Deploy Holesky Windows Beacon Nodes
  become: true
  hosts:
    - nimbus-holesky-windows
  vars_files: layout/holesky.yml
  tasks:
    - include_role: name=infra-role-beacon-node-windows
      with_items: '{{ nodes_layout[hostname] }}'
      loop_control: { loop_var: node, index_var: idx }
