---
- name: Verify Ansible versions
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./versioncheck.py
      changed_when: false

- name: Deploy Holesky linux hosts
  become: true
  serial: '{{ serial|default(1) }}'
  hosts: nimbus-holesky-linux
  vars_files: layout/holesky.yml
  roles:
    - { role: swap-file,         tags: [ swap-file ]        }
    - { role: open-ports,        tags: [ open-ports ]       }
  tasks:
    - include_role: name=infra-role-geth
      when: node.el == "geth"
      with_items: '{{ nodes_layout[hostname] }}'
      loop_control: { loop_var: node, index_var: idx }

    - include_role: name=infra-role-geth-exporter
      when: node.el == "geth"
      with_items: '{{ nodes_layout[hostname] }}'
      loop_control: { loop_var: node, index_var: idx }

    - include_role: name=infra-role-erigon
      when: node.el == "erigon"
      with_items: '{{ nodes_layout[hostname] }}'
      loop_control: { loop_var: node, index_var: idx }

    - include_role: name=infra-role-nethermind
      when: node.el == "nethermind"
      with_items: '{{ nodes_layout[hostname] }}'
      loop_control: { loop_var: node, index_var: idx }

    - include_role: name=infra-role-beacon-node-linux
      with_items: '{{ nodes_layout[hostname] }}'
      loop_control: { loop_var: node, index_var: idx }

    - include_role: name=infra-role-validator-client
      with_items: '{{ nodes_layout[hostname] }}'
      when: validator_client_service_enabled
      loop_control: { loop_var: node, index_var: idx }
