---
- name: Verify Ansible versions
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./roles.py --check
      changed_when: false

- name: Deploy Hoodi Linux Misc Services
  become: true
  serial: '{{ serial|default(1) }}'
  hosts:
    - nimbus-hoodi-geth
    - nimbus-hoodi-geth-macm2
    - nimbus-hoodi-nec
    - nimbus-hoodi-neth
  vars_files: layout/hoodi.yml
  roles:
    - { role: update-netplan,                 tags: update-netplan,     when: ansible_system == 'Linux' }
    - { role: infra-role-swap-file,           tags: swap-file           }
    - { role: infra-role-open-ports,          tags: open-ports          }
    - { role: redirect-ports,                 tags: redirect-ports,     when: redirect_ports is defined }
    - { role: nimbus-era-files,               tags: nimbus-era-files,   when: era_files_path is defined }
    - { role: infra-role-mev-boost,           tags: mev-boost,          when: mev_boost_enabled == true }
    - { role: infra-role-nimbus-light-client, tags: nimbus-light-client }

- name: Deploy Hoodi Linux Beacon Nodes
  become: true
  serial: '{{ serial|default(1) }}'
  hosts:
    - nimbus-hoodi-geth
    - nimbus-hoodi-nec
    - nimbus-hoodi-neth
  vars_files: layout/hoodi.yml
  tasks:
    - include_role:
        name: infra-role-beacon-node-linux
        apply:
          tags: always
      tags: [ beacon-node ]
      with_items: '{{ nodes_layout[inventory_hostname] }}'
      loop_control: { loop_var: node, index_var: idx }
    - include_role:
        name: infra-role-validator-client
        apply:
          tags: always
      tags: [ validator-client ]
      with_items: '{{ nodes_layout[inventory_hostname] }}'
      when: validator_client_service_enabled
      loop_control: { loop_var: node, index_var: idx }

- name: Deploy Hoodi Geth Nodes
  become: true
  serial: '{{ serial|default(1) }}'
  hosts:
    - nimbus-hoodi-geth
    - nimbus-hoodi-geth-macm2
  vars_files: layout/hoodi.yml
  tasks:
    - include_role:
        name: infra-role-geth
        apply:
          tags: always
      tags: [ geth ]
      when: node.el == "geth"
      with_items: '{{ nodes_layout[inventory_hostname] }}'
      loop_control: { loop_var: node, index_var: idx }

    - include_role:
        name: infra-role-geth-exporter
        apply:
          tags: always
      tags: [ geth-exporter ]
      when: node.el == "geth"
      with_items: '{{ nodes_layout[inventory_hostname] }}'
      loop_control: { loop_var: node, index_var: idx }

- name: Deploy Hoodi Nethermind Nodes
  become: true
  serial: '{{ serial|default(1) }}'
  hosts: nimbus-hoodi-neth
  vars_files: layout/hoodi.yml
  tasks:
    - include_role:
        name: infra-role-nethermind
        apply:
          tags: always
      tags: [ nethermind ]
      when: node.el == "nethermind"
      with_items: '{{ nodes_layout[inventory_hostname] }}'
      loop_control: { loop_var: node, index_var: idx }

- name: Deploy Hoodi Nimbus ETH1 Nodes
  become: true
  serial: '{{ serial|default(1) }}'
  hosts: nimbus-hoodi-nec
  vars_files: layout/hoodi.yml
  tasks:
    - include_role:
        name: infra-role-nimbus-eth1
        apply:
          tags: always
      tags: [ nimbus-eth1 ]
      when:
        - "'el' in node"
        - node.el == "nec"
      with_items: '{{ nodes_layout[inventory_hostname] }}'
      loop_control: { loop_var: node, index_var: idx }

- name: Deploy Hoodi MacOS Beacon Nodes
  become: true
  hosts:
    - nimbus-hoodi-macm2
  vars_files: layout/hoodi.yml
  tasks:
    - include_role:
        name: infra-role-beacon-node-macos
        apply:
          tags: always
      tags: [ beacon-node ]
      with_items: '{{ nodes_layout[inventory_hostname] }}'
      loop_control: { loop_var: node, index_var: idx }
