---
- name: Verify Ansible versions
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./roles.py --check
      changed_when: false

- name: Deploy Nimbus Light Client
  become: true
  hosts:
    - nimbus-holesky-geth
    - nimbus-holesky-erigon
    - nimbus-holesky-neth
  roles:
    - { role: infra-role-open-ports,          tags: open-ports }
    - { role: infra-role-nimbus-light-client, tags: light-client }
