---
- name: Verify Ansible versions
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./roles.py --check
      changed_when: false

- name: Configure Nimbus Portal Network nodes
  become: true
  hosts:
    - nimbus-portal-metal
  pre_tasks:
    - name: Enable Maintenance Mode
      command: 'maintenance Ansible run by {{ lookup("env", "USER") }}'
      tags: always
  post_tasks:
    - name: Disable Maintenance Mode
      command: 'maintenance disable'
      tags: always
  roles:
    # Extra 32 or 64 IPv4 addresses for each of the nodes on the host.
    - { role: update-netplan,               tags: update-netplan    }
    - { role: infra-role-swap-file,         tags: swap-file         }
    - { role: infra-role-open-ports,        tags: open-ports        }
    - { role: infra-role-beacon-node-linux, tags: beacon-node-linux }
    - { role: infra-role-nimbus-eth1,       tags: nimbus-eth1       }
  tasks:
    - include_role:
        name: infra-role-nimbus-portal-client
        apply:
          tags: always
      tags: [ nimbus-portal-client ]
      with_sequence: start=1 end={{ nimbus_portal_client_host_number_of_public_ips }}
      loop_control:
        loop_var: index

- name: Configure Nimbus Portal Bridge
  become: true
  vars_files: portal-bridge.yml
  hosts:
    - metal-01.ih-eu-mda1.nimbus.portal
  pre_tasks:
    - name: Enable Maintenance Mode
      command: 'maintenance Ansible run by {{ lookup("env", "USER") }}'
      tags: always
  post_tasks:
    - name: Disable Maintenance Mode
      command: 'maintenance disable'
      tags: always
  roles:
    - { role: infra-role-open-ports,           tags: open-ports    }
    - { role: infra-role-nimbus-portal-client, tags: nimbus-client }
    - { role: infra-role-portal-bridge,        tags: portal-bridge }
