---
- name: verify ansible versions
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./roles.py --check
      changed_when: false

- name: Configure Nimbus Portal Bridge
  become: true
  vars_files: portal-bridge.yml
  hosts:
    - metal-01.ih-eu-mda1.nimbus.fluffy
  roles:
    - { role: infra-role-nimbus-fluffy, tags: nimbus-fluffy }
    - { role: infra-role-portal-bridge, tags: portal-bridge }
