- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git

- name: infra-role-bootstrap-windows
  src: git@github.com:status-im/infra-role-bootstrap-windows.git

- name: infra-role-bootstrap-macos
  src: git@github.com:status-im/infra-role-bootstrap-macos.git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git

- name: infra-role-open-ports
  src: git@github.com:status-im/infra-role-open-ports.git

- name: infra-role-swap-file
  src: git@github.com:status-im/infra-role-swap-file.git

- name: infra-role-nginx
  src: git@github.com:status-im/infra-role-nginx.git
  version: 7186070dc036f6df2a51781cb831dd340a1db054

- name: infra-role-origin-certs
  src: git@github.com:status-im/infra-role-origin-certs.git
  version: 74dc0d13f0c2181e0e13676f128dc1a009afb9fc

- name: infra-role-oauth-proxy
  src: git@github.com:status-im/infra-role-oauth-proxy.git
  version: ca0c1964e34df6e19280882db266ec7ceea8fcdf

- name: infra-role-consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  version: 16d9af36f69c6cb5fd61a6e13f011a96f279af6f

- name: infra-role-beacon-node-linux
  src: git@github.com:status-im/infra-role-beacon-node-linux.git
  version: 0a62bc585f2987876ac30a8213e1ea2bc943667c

- name: infra-role-beacon-node-windows
  src: git@github.com:status-im/infra-role-beacon-node-windows.git
  version: c4f1c8194608452c5705787d62d341c498550e1c

- name: infra-role-beacon-node-macos
  src: git@github.com:status-im/infra-role-beacon-node-macos.git
  version: 9dc8dd7df3e31259e4ad4184eeed13dd0f16d378

- name: infra-role-validator-client
  src: git@github.com:status-im/infra-role-validator-client.git
  version: 4321fd2dda41434b7d13b4719d667a19b0922aab

- name: infra-role-nimbus-eth1
  src: git@github.com:status-im/infra-role-nimbus-eth1.git
  version: 74524a6c831e37e2710c18693237989a11a5520f

- name: infra-role-nimbus-portal-client
  src: git@github.com:status-im/infra-role-nimbus-portal-client.git
  version: afa3142dac9a6f05a4f07b6aed5f99e32b160c26

- name: infra-role-portal-bridge
  src: git@github.com:status-im/infra-role-portal-bridge.git
  version: 73017032539bd80c02b9f270e5c60d08b90cfd49

- name: infra-role-dist-validators
  src: git@github.com:status-im/infra-role-dist-validators.git
  version: 0431a8cb30b3436fa61fc66854d57d98bbfdd5c5

- name: infra-role-rocketpool
  src: git@github.com:status-im/infra-role-rocketpool.git
  version: d33b55df07fb4f21286bf9a138fa086d0c024684

- name: infra-role-winsw
  src: git@github.com:status-im/infra-role-winsw.git
  version: 22b41bce7e2d6de1a13b9e53e6f7a278a29b948e

- name: infra-role-kibana
  src: git@github.com:status-im/infra-role-kibana.git
  version: 32c6f04d83605dcd0b42dc41857faea8cba925e8

- name: infra-role-elasticsearch
  src: git@github.com:status-im/infra-role-elasticsearch.git
  version: 54493cc5f0f9efc57c29b380b141e932d0c439fc

- name: infra-role-elasticsearch-lb
  src: git@github.com:status-im/infra-role-elasticsearch-lb.git
  version: 5cf124f24d386b6c19dc9a01a0b1c3f3f2e8a3c5

- name: infra-role-vault-pki
  src: git@github.com:status-im/infra-role-vault-pki.git
  version: c1892667bd905f40bf8334c1fe9ad267ec14a1e0

- name: infra-role-systemd-timer
  src: git@github.com:status-im/infra-role-systemd-timer.git
  version: 632ffdde287858135e55941b37cdd4ac017193e6

- name: infra-role-launchd-timer
  src: git@github.com:status-im/infra-role-launchd-timer.git
  version: 4e4c6da774d8007d9a3563322cbce2e215be5bb1

- name: infra-role-geth
  src: git@github.com:status-im/infra-role-geth.git
  version: f346c9cadc099356e5975809d4875100eded99c0

- name: infra-role-geth-exporter
  src: git@github.com:status-im/infra-role-geth-exporter.git
  version: 198b14093926716e17318f2c0fab661347d5db75

- name: infra-role-erigon
  src: git@github.com:status-im/infra-role-erigon.git
  version: 33d5e2041b98dcd3f12c580a2f1109b5258a52e8

- name: infra-role-nethermind
  src: git@github.com:status-im/infra-role-nethermind.git
  version: 575b8cb6a1b5e5b334ba04ecaab0c62731755869

- name: infra-role-smart-metrics
  src: git@github.com:status-im/infra-role-smart-metrics.git
  version: 656d98e86a9a78db02e3001f72a148504f8f416a

- name: infra-role-mev-boost
  src: git@github.com:status-im/infra-role-mev-boost.git
  version: d83dd0007068a586df1f14743fe5d7eebaa5581c

- name: infra-role-nimbus-bench-eth1
  src: git@github.com:status-im/infra-role-nimbus-bench-eth1.git
  version: 29dcb23bd9f2f7e8060ed58480721548442e369e

- name: infra-role-nimbus-light-client
  src: git@github.com:status-im/infra-role-nimbus-light-client.git
  version: 093a071539a2f036bbf7d9118ea4649160561a86

- name: infra-role-rpc-snooper
  src: git@github.com:status-im/infra-role-rpc-snooper.git
  version: fc8f4d5a1dad3c004b4f8f2fc020751324511539

- name: infra-role-aztec
  src: git@github.com:status-im/infra-role-aztec.git
  version: 2caa72cc15ba66fa44354d094d5bb01badc55545

- name: infra-role-commit-boost
  src: git@github.com:status-im/infra-role-commit-boost.git
  version: 9910a0e12555ea66f17a7859e4eb35ed27a9968e

- name: infra-role-reth
  src: git@github.com:status-im/infra-role-reth.git
  version: 8bcef96c013906e6456bb3358f3c3d25b525937d

- name: infra-role-lighthouse
  src: git@github.com:status-im/infra-role-lighthouse.git
  version: ab172425fbc4f0452777796aed4620ac13f060fd

- name: infra-role-eth-validator-watcher
  src: git@github.com:status-im/infra-role-eth-validator-watcher.git
  version: b57138ce67712a460367721eff47e56113ec3f3f
