---
- name: Verify Ansible versions
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./roles.py --check
      changed_when: false

- name: Deploy Spolia Testnet nodes
  become: true
  serial: '{{ serial|default(1) }}'
  vars_files: layout/sepolia.yml
  hosts:
    - nimbus-sepolia-linux
  roles:
    - { role: update-netplan,           tags: [ update-netplan ], when: ansible_system == 'Linux' }
    - { role: infra-role-open-ports,    tags: [ open-ports ]        }
    - { role: infra-role-smart-metrics, tags: [ smart-metrics ]     }
    - { role: redirect-ports,           tags: [ redirect-ports ]    }
    - { role: nimbus-era-files,         tags: [ nimbus-era-files ]  }
  tasks:
    - include_role:
        name: infra-role-geth
        apply:
          tags: always
      tags: [ geth ]
      with_items: '{{ nodes_layout[hostname] }}'
      loop_control:
        loop_var: node
        index_var: idx

    - include_role:
        name: infra-role-beacon-node-linux
        apply:
          tags: always
      tags: [ beacon-node ]
      with_items: '{{ nodes_layout[hostname] }}'
      loop_control:
        loop_var: node
        index_var: idx

    - include_role:
        name: infra-role-validator-client
        apply:
          tags: always
      tags: [ validator-client ]
      with_items: '{{ nodes_layout[hostname] }}'
      when: validator_client_service_enabled
      loop_control:
        loop_var: node
        index_var: idx
