---
- name: Verify Ansible versions
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./versioncheck.py
      changed_when: false

- name: Deploy Spolia Testnet nodes
  become: true
  serial: '{{ serial|default(1) }}'
  hosts:
    - nimbus-sepolia-metal
  tasks:
    - include_role: name=infra-role-geth
      tags: [ geth, infra-role-geth ]
      with_items: '{{ nodes_layout[hostname] }}'
      loop_control:
        loop_var: node
        index_var: idx
